### ISSUE TITLE
submit to curators button

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2106] opened 2019-11-11 12:01 UTC
Does not seem to be working for me (pombase canto) , but it could be my connection?

**Comment by ValWood** [comment] 2019-11-11 12:02
no it seems to be the button...

**Comment by ValWood** [comment] 2019-11-11 12:03
curs/00c35706b38fef88

**Comment by jseager7** [comment] 2019-11-11 12:44
Is this a duplicate of https://github.com/pombase/canto/issues/2105? The discussion there implied that this issue was fixed, but we should probably re-open the linked issue if it's not.

**Comment by ValWood** [comment] 2019-11-11 13:58
#2105 is different and was fixed.

I can now see the button in blue, but when I click it, nothing happens...

**Comment by kimrutherford** [comment] 2019-11-11 19:38
Sorry about that.  I broke it while fixing #2105.  Fixed now.

**Closed by kimrutherford** 2019-11-11 19:38 UTC
