### ISSUE TITLE
Export GO GAF from PHI Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2098] opened 2019-11-06 10:55 UTC
will this be possible for approved sessions. Then we can expediate submission of the GO data to Uniprot

(Will need to set up some things for this, @mah11  can advise)

**Comment by mah11** [comment] 2019-11-06 11:02
> @mah11 can advise

I question this assertion ;)

(... but maybe it'll turn out to be accurate, depending on what, if any, specific issues arise)

**Comment by kimrutherford** [comment] 2019-11-06 11:04
Do we need to export GAF files directly from Canto or could it be done from the main PHI-base database?

For PomBase we load all annotations into Chado, then filter and export as GAF.

**Comment by ValWood** [comment] 2019-11-06 11:17
I can't remember how to get GAFS into GO. ;)

I guess it could be done from PHIBAse but I don't know how long this would take.  I will ask @jseager7 to add to the next agenda. If it is a long time I think we should export  because I don't want the Uniprot curators to curate the papers we have done. This is likely to happen becasue we are requesting name  updates, and I think name updates can only be done  alongside entry updates.

I thought it might  be easy to export as I thought it was done for Ruth when she was using Canto for teaching.

We can discuss anyway, but it is something that needs to happen.

**Comment by jseager7** [comment] 2019-11-06 11:33
I've added this to the next agenda.

Ideally, would we need to extract data from PHI-base too, or just the Canto curation sessions? Pulling data out of PHI-base should be fairly easy since the data also exists as a flat table format.

**Comment by ValWood** [comment] 2019-11-06 11:38
OK in that case we can export only  from PHIBase.

Could you look into exporting a GAF at some point. Later we will need to move to GPAD so you might want to do both simultaneously ....

**Comment by jseager7** [comment] 2019-11-06 12:23
> Could you look into exporting a GAF at some point.

I've done some investigation, and the main problem with this is that historically, PHI-base stopped collecting data on GO annotations. In the current schema (version 4.x), there's a column for GO annotations in the PHI-base table, but over 94% of it is empty. That means we don't have GO evidence codes for 94% of the records in PHI-base, and presumably that means we can't export a compliant GAF file.

Now, the new Canto data should be compliant with the GAF format, but the problem is that data can't be integrated into PHI-base until we've migrated PHI-base to a new schema (version 5), and I don't know when that's likely to be complete. With that in mind, it will probably be better to map from Canto's schema to the GAF file format (considering the new PHI-base schema is probably going to be based on Canto's schema anyway).

**Comment by ValWood** [comment] 2019-11-06 13:17
Sounds like a good plan. It shouldn't be too complicated, and it might be useful for other users who decide to curate but do not yet have a database so it would be good to be able to export GO diretcly from Canto...

**Comment by kimrutherford** [comment] 2019-11-06 19:34
If checked and you're right Val, it is possible to export GAF files from Canto, more or less.  I hadn't forgotten that.  Unfortunately the code is a bit broken at the moment but shouldn't take more than and hour or two to fix.

**Comment by ValWood** [comment] 2019-11-06 20:52
OK that's probably the fastest way to get things working for PHI-base. Maybe @jseager7 can look at that?

**Comment by kimrutherford** [comment] 2019-11-07 01:49
The Canto GAF export code wasn't far from working so I fixed it.  James you can now export GAF files with commands like:

./script/canto_export.pl gaf --annotation-type=molecular_function > molecular_function.gaf
./script/canto_export.pl gaf --annotation-type=cellular_component > cellular_component.gaf
./script/canto_export.pl gaf --annotation-type=biological_process > biological_process.gaf

The code isn't well tested yet but I thought I'd commit the changes so you can try it.

**Comment by kimrutherford** [comment] 2019-11-07 06:00
> The code isn't well tested yet but I thought I'd commit the changes so you can try it.

I've now done some testing.  The output looks quite close to what we get by exported from Chado.

I noticed that the output had "gene" in column 12 / "DB Object Type" which isn't a valid value according the GAF documentation.  I've changed it to "protein".

Is it OK to have vertical bar separators in the extensions like this?:

```
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       gene    taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPBC3F6.03)|has_regulation_target(PomBase:SPCC757.07c)|has_regulation_target(PomBase:SPAC3C7.14c)|has_regulation_target(PomBase:SPCC18B5.01c)|has_regulation_target(PomBase:SPCC663.03)
```

In the PomBase GAF these are split into multiple lines:

```
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       protein taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPBC3F6.03)
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       protein taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPCC757.07c)
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       protein taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPAC3C7.14c)
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       protein taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPCC18B5.01c)
PomBase SPAC24B11.06c   sty1            GO:0036091      PMID:9585505    IMP             P       MAP kinase Sty1 phh1|spc1       protein taxon:4896      20120301        PomBase has_regulation_target(PomBase:SPCC663.03)
```

I can't see anything in the GAF docs about the vertical bars.

**Comment by ValWood** [comment] 2019-11-07 09:18
@mah can you answer any gaf format questions and check for compliance?

We also need to do something  for the taxon colum so if an annotation has genes from both species (i.e. a physical interaction) it gets both taxons.
I thought I had already opened a ticket about this but I can't find it...

**Comment by kimrutherford** [comment] 2019-11-07 09:28
> i.e. a physical interaction

That wouldn't be a GO annotation would it?

**Comment by ValWood** [comment] 2019-11-07 09:50
I mean a "protein binding" annotation

**Comment by jseager7** [comment] 2019-11-07 10:09
@kimrutherford I've double checked whether the pipe character can be used to separate annotation extensions and it looks like it can:

"...where a gene product carries out its activity in different places or under different circumstances, then multiple annotation extension 'relationship(identifier)' pairs should be added into the annotation extension field of the same annotation and be separated from each other with a pipe [...] it would be equally correct to represent the annotation extension data in separate annotation lines."

Source: [GO Wiki](http://wiki.geneontology.org/index.php/Annotation_Extension#Use_of_the_Pipe_to_separate_Annotation_Extension_values)

**Comment by kimrutherford** [comment] 2019-11-07 11:05
> I've double checked whether the pipe character can be used to separate annotation
> extensions and it looks like it can

Thanks for checking!  It sounds like we're good to go for GAF export.

I've just spoken to Val and Midori about the taxon column and we think that it's probably OK just having one taxon ID.  If the GO GAF checker doesn't like it, we'll fix it then.

**Comment by mah11** [comment] 2019-11-07 13:03
I also noted in our chat that changes to the GO pipeline mean that I can no longer do any useful automated checks locally :/

**Comment by jseager7** [comment] 2019-12-02 14:40
@kimrutherford I've tested this on the demo server and it seems to work fine when there are GO annotations in at least one session. However, the script doesn't seem to be handling the case where there aren't any GO annotations, which I saw on my local copy (with the verbose flag on):

```
Use of uninitialized value $count in numeric gt (>) at /canto/script/canto_export.pl line 92.
no sessions exported
Use of uninitialized value $results in print at /canto/script/canto_export.pl line 99.
```

**Comment by jseager7** [comment] 2019-12-02 15:10
One small issue that I've noticed with the export is that the 'DB' and 'Assigned By' columns are still using 'PomBase' as the database name, when it should really be 'PHI-base'. Does the script read the database name from the `canto_deploy` file?

**Comment by kimrutherford** [comment] 2019-12-02 20:35
Hi James.

I forgot that the GAF file exporting has its own config.  You can override the defaults by putting something like this in your canto_deploy.yaml:

```yaml
export:
  gene_association_fields:
    db: "PomBase"
    assigned_by: "PomBase"
```

**Comment by jseager7** [comment] 2019-12-03 12:25
I've tested the config and it works fine, thanks. I'm going to close this for now since nothing else needs to be done to enable GAF export. @ValWood please let me know anytime you want the approved sessions to be exported.

**Closed by jseager7** 2019-12-03 12:25 UTC
Labels: PHI-Canto

**Comment by ValWood** [comment] 2019-12-04 10:14
OK, early in the year once we have some sessions finalised we will do a submission.

**Comment by ValWood** [comment] 2020-03-26 17:00
I will open a new ticket for the next steps
