### ISSUE TITLE
Same genotype, multiple backgrounds

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2600] opened 2022-08-01 08:38 UTC
@kimrutherford @ValWood 

When curating PMID:15857958, I am trying to have the same genotype with and without a certain background. In this case, pdk1D with and without cdc25-22. Is it possible to do it? I try copy and edit, but since the background field is not in the `copy and edit` window, I cannot make changes, so can't copy.

**Comment by ValWood** [comment] 2022-08-01 09:08
This  is a known bug. 
There is a work-around. You can't copy edit and *only* change the background.
But you can copy, edit the allele (or some other content), add the background, revert the  changed content (a bit of a faff!)

**Comment by kimrutherford** [comment] 2022-08-01 09:08
Here's some more detail: https://github.com/pombase/canto/issues/1519

We should fix this!

**Comment by ValWood** [comment] 2022-08-01 09:09
https://github.com/pombase/canto/issues/1519

**Comment by ValWood** [comment] 2022-08-01 09:10
OK, let's discuss next time we chat! I'm so used to it I forget it is a bug!

**Comment by manulera** [comment] 2022-08-01 09:40
Ok got it, thanks! We can close after we discuss it

**Comment by ValWood** [comment] 2022-11-19 22:43
closing as duplicate of https://github.com/pombase/canto/issues/1519
I

**Closed by ValWood** 2022-11-19 22:43 UTC
