### ISSUE TITLE
Wild-type strains don't display on metagenotype page

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1882] opened 2019-05-21 09:51 UTC
Since upgrading to AngularJS 1.7.8 in #1874, it seems the wild-type strains no longer display on the metagenotype page.

I think this is to due with a change in `$watch` logic in newer versions of AngularJS. Previously I was trying to prevent the strains being loaded when `selectedOrganism` was initialised (since it defaults to `null`), but this code never seemed to trigger at all in the new AngularJS version:

```js
$scope.$watch('selectedOrganism', function (newVal, oldVal) {
  if (newVal !== oldVal) {
    $scope.loadWildTypeStrains();
  }
});
```
I guess what I really wanted to check was just that the selected organism wasn't `null`, so the fix below is more sensible, and works without any errors in the console:
```js
$scope.$watch('selectedOrganism', function () {
  if ($scope.selectedOrganism) {
    $scope.loadWildTypeStrains();
  }
});
```
I'll open a pull request to fix this.

**Comment by kimrutherford** [comment] 2019-05-21 10:36
I've just checked my local Canto and I can see the wild type strains even without this change.  I also checked in the debugger and the `$scope.loadWildTypeStrains();` in the $watch callback gets hit (I added a breakpoint).  Could there be another problem?

**Comment by jseager7** [comment] 2019-05-21 10:44
> Could there be another problem?

I'm not sure. I seem to get this problem on Chrome, on the `master` branch (commit 3a4b5a5944eae7f29fd35015233e32e2731dadb1), after reloading without cache.

The bug might be particular to the case where there's a session with only one host organism (so the host organism is automatically set when you go to the Metagenotype Management page). I can reliably trigger the bug by switching between the branch that fixes the bug (`1882-fix-organism-watcher`) and `master`, as long as I reload without cache.

**Comment by kimrutherford** [comment] 2019-05-21 11:27
> I seem to get this problem on Chrome, on the master branch (commit 3a4b5a5), after reloading
> without cache.

I'm doing the same, including using Chrome for testing.

> The bug might be particular to the case where there's a session with only one host organism

I just tried a session with only one host organism and the wild-type strain list appeared correctly.  Very strange.

I've tried the same thing with your change and that worked too.

**Comment by kimrutherford** [comment] 2019-05-21 11:30
I should have said, even though I can't reproduce the bug I think you should merge your fix because it looks more correct than the existing code.

**Comment by jseager7** [comment] 2019-05-21 11:31
>  I think you should merge your fix because it looks more correct than the existing code.

I agree. That should cover the possibility of anyone else being affected by this bug in future anyway. I'll go ahead and merge.

**Closed** 2019-05-21 11:32 UTC
Labels: PHI-Canto, bug, high priority
