### ISSUE TITLE
specifying taxon for  multi-species processes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2394] opened 2021-01-25 19:12 UTC
Currently looks like this:

<img width="1173" alt="Screenshot 2021-01-25 at 16 50 28" src="https://user-images.githubusercontent.com/7359272/105753751-14b74480-5f41-11eb-9767-3720aa89ccc9.png">

But can we make it cleverer? The user should not need to specify the  pathogen if they are curating the pathogen, or to specify the host if they are curating the host. These parts of the taxon field could be inferred from the entry being annotated.

**Comment by kimrutherford** [comment] 2021-01-25 23:25
> These parts of the taxon field could be inferred from the entry being annotated.

What do you mean by "entry" here?

**Comment by ValWood** [comment] 2021-01-26 08:26
The GO annotation is single species and is applied to a specific Uniprot ID. We  usually infer that taxon ID automatically for GO. We only need to add the taxon ID of the interacting species. We  don't need to replicate the taxon ID of the species we are annotating the GO term to. Does that make sense?

**Comment by jseager7** [comment] 2021-01-26 09:37
Closing, since this seems like a duplicate of issue #2335. I think I have everything I need in place to fix it, I just haven't found time to work on it yet.

**Closed by jseager7** 2021-01-26 09:37 UTC
Labels: PHI-Canto
