### ISSUE TITLE
penetrance:unknown

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1305] opened 2017-01-10 15:25 UTC
Spotted this last night.
PMID:26258632
curs/558b22ef42aa6ec2/ro

Is this not reported in logs (I assume not as I haven't done any mad1 for ages...)
![default](https://cloud.githubusercontent.com/assets/7359272/21811692/84c8181a-d748-11e6-887a-03e8db3249e1.jpg)

**Comment by ValWood** [comment] 2017-01-10 15:29
oddly it only seems to show like this on the summary page. On the Mad1 page it is has_penetrance 1.5%

**Comment by mah11** [comment] 2017-01-10 17:12
duplicate of #1272

**Closed** 2017-01-26 23:50 UTC
