### ISSUE TITLE
find genotype by name

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#776] opened 2015-03-18 14:14 UTC
This is probably low priority, but was on the wiki:

Offer an option to search for genotypes by genotype name on the "find an existing genotype" page.

Original comment by: mah11

**Comment by ValWood** [comment] 2016-01-28 20:02
Is this covered by
https://github.com/pombase/canto/issues/808

**Comment by ValWood** [comment] 2016-03-10 09:00
parking this one for now. Not sure if we need it?

**Comment by ValWood** [comment] 2019-02-09 20:13
duplicate of #808

**Closed by ValWood** 2019-02-09 20:13 UTC
Labels: blue sky, feature request, future, sourceforge
