### ISSUE TITLE
Pathogen-host interaction phenotype extension

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1960] opened 2019-06-19 06:23 UTC
We would like to establish a  phenotype extension option for 
"disease_causing_ability"

This will be an option on all pathogen host interactions initially. Gradually @CuzickA  will refine when the option is available with a config file. (we can open a ticket for that point once the extension is working)

This will allow  any phenotypic observation 
e.g 
PHIPO:0000445 Pathogen host interaction host cell death phenotype
PHIPO:0000xxx abnormal pathogen growth in host post penetration 
etc

(or children) to be linked to the appropriate changes in pathogenicity and virulence without precomposing every single option.

The root term for the extension is "pathogenicity phenotypes"
The extension will be "disease causing ability" for now. We might be able to improve this label later.

**Comment by ValWood** [comment] 2019-06-19 06:29
This method of annotation  will allow you to "instantiate" the annotations in the extensions to give you the annotation to the required high-level term.

This way, in addition to reducing the ontology development burden  we will
 improve annotation consistency (users will not need to make concurrent annotations, in these situations they are always inclined to forget one). Also the disease-causing ability terms" are a little abstract as phenotypes (in fact, they aren't really *just* phenotypes, they are changes in phenotypes), so they would be difficult to find if you are really only thinking about observations. Overall we will improve the likelihood that all the information we want will be correctly captured.
I can illustrate on the next call how this will work by analogy to the  GO MF part_of BP annotation extensions.

**Comment by jseager7** [comment] 2019-06-19 09:22
I think this sounds like a good idea (presuming I'm understanding it correctly).

One issue with the naming that I can immediately see is that 'disease_causing_ability' is very similar linguistically to 'causes_disease' (with the display name 'disease caused'), which is the annotation extension we use to annotate the _specific_ disease caused by a pathogen (for example, Fusarium ear blight). This currently applies to every child of PHIPO:0000001 'pathogen host interaction phenotype', so it's likely users will see both extensions at the same time.

Perhaps something like 'pathogenic ability' or 'infective ability' would be a better first choice?

**Comment by ValWood** [comment] 2019-06-19 09:55
Yes good point, or maybe "extent of infectivity"

So  see what @martin2urban @CuzickA  and  Kim think would be the best label

But to me the specific disease shouldn't be an extension of the phenotypes, it's an annotation that belongs on the species and the gene. The phenotype doesn't cause the disease its an 'output' of the disease. We can discuss this later.

**Comment by jseager7** [comment] 2019-06-19 09:59
> But to me the specific disease shouldn't be an extension of the phenotypes, it's an annotation that belongs on the species and the gene.

That's useful to know. I presume we could always re-target the extension to use a gene as its target instead?

To be honest, I don't know if the specific disease annotations have been very widely used (if at all). @CuzickA can probably answer that.

**Comment by ValWood** [comment] 2019-06-19 10:04
It's a good thing to record but I don't think we would want to add to every phenotype, particularly as for a given pathogen the same disease would be annotated to nearly every phenotype. It might be useful if a pathogen causes 2 separate diseases with different phenotypes. How common is this? Anyway it might not be the best way. Most databases treat disease as an independent gene-level annotation (this is a disease related gene, phenotypes could be attached to the disease description).

**Comment by CuzickA** [comment] 2019-06-19 10:06
Are we saying here that the 'disease caused' AE should be linked to the metagenotype rather than the phenotype?

**Comment by CuzickA** [comment] 2019-06-19 10:08
@ValWood just seen your comment above
The disease name may change dependent on the host tissue infected eg Fusarium ear blight and Fusarium stem rot.

**Comment by jseager7** [comment] 2019-06-20 10:35
@ValWood Here's a draft version of the definition files:

## phipo_extensions.tsv

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000001 | is_a | infective_ability | PHIPO:0000006 | extent of infectivity | extent of change in pathogenicity and virulence | * | user

PHIPO:0000001 is 'pathogen host interaction phenotype'. PHIPO:0000006 is 'pathogenicity phenotype'.

### Questions

* I've set the cardinality to `*` (zero or more). Should it be more restricted than this?

* Do you want me to use 'extent of infectivity' for both the extension relation and the display text? That is, should these properties be consistently named?

* Does the help text accurately describe the extension?

## phipo_extension_relations.obo

```
[Typedef]
id: infective_ability
name: infective_ability
def: ?
synonym: ?
comment: ?
property_value: ?
```
I don't think I have enough knowledge about the biology or the semantics of this extension to fill in the blanks above. I could just leave them absent for now, but if anyone else can think of any values for those missing properties, I'll gladly fill them in. Here's my best attempt at the definition:

> Relation between a pathogen host interaction phenotype and its observed pathogenicity and virulence. Pathogenicity is the ability of a pathogen to produce infectious disease. Virulence is the severity of an infectious disease.

(I took the definitions of pathogenicity and virulence from PATO.)

**Comment by ValWood** [comment] 2019-06-20 10:58
Yes that all looks fine. @CuzickA  can you test  and if so this can close. we can open new tickets for future changes, and for the configuration file.

**Comment by jseager7** [comment] 2019-06-20 13:17
I hadn't actually enabled this extension when I commented before, but it should be enabled on the main server by the end of today or the start of tomorrow.

**Comment by jseager7** [comment] 2019-06-20 13:42
This is enabled on the main server now:

![image](https://user-images.githubusercontent.com/37659591/59853736-63fec180-9369-11e9-89ee-ac4d08f2601b.png)

Now I'm presuming it needs to be tested by curators, so I'm going to un-assign myself from this issue for now. Please assign me again if you need any changes to the extension.

**Comment by CuzickA** [comment] 2019-06-21 09:21
Testing on GT2 paper curation
Have added 'reduced virulence' to top metagenotype annotation 'decreased filamentous growth on host surface'
The other annotations already use 'reduced virulence' as the main phenotype term but don't record an actual observation eg decreased pathogen growth or host lesions etc. We will need to decide when to use 'reduced virulence' as the main term vs when to use as an AE for a disease observation (pathogen growth/host lesion etc).
![image](https://user-images.githubusercontent.com/11753634/59912054-23588400-940d-11e9-9f2e-7f9a102f69d2.png)

**Comment by CuzickA** [comment] 2019-06-21 10:11
Testing for Tox1/Snn1 paper curation

This looks really nice for connecting observed 'cell death phenotype' to 'pathogenicity phenotype' in this example
![image](https://user-images.githubusercontent.com/11753634/59913220-ab3f8d80-940f-11e9-9d98-7aadf5c64691.png)

Other examples are more complicated and will require discussion @ValWood on our next call
Eg
![image](https://user-images.githubusercontent.com/11753634/59915267-21de8a00-9414-11e9-9b7e-53072c56cf65.png)

![image](https://user-images.githubusercontent.com/11753634/59913599-59e3ce00-9410-11e9-91ec-bc1d0dfa900d.png)
In this interaction the pathogen has gained pathogenicity (Tox1+) but the mutation in the host gene (Snn1-) means that the pathogen Tox1 can no longer interact with the host Snn1 to trigger cell death and disease. This changes the interaction from virulent to avirulent. 
What is the wt metagenotype we are comparing to here?
Is it
1)Tox1+(prescence unknown) Pn (Sn79-1087) / Snn1+ (wt) Ta (Chinese spring) (Fig 5B This is the control for the pathogen transformant)
or 
2) Sn2000-Tox1A1(transformant) Pn (Sn79-1087) / Snn1+ (wt) Ta (Chinese spring) ( Fig 5B This is the control for mutation of the host gene)

In 2) we could ignore the 'gain of pathogenicity' and just assume this pathogen genotype is pathogenic, Then we would want to capture the shift from virulence to avirulence. We don't really have a term for 'avirulence' yet. It is more than 'reduced virulence' but it is not 'loss of pathogenicity' as the pathogen has the ability to cause disease on a wt host genotype (Snn1+).

Do we also need to connect up 'Effector' as an AE or are we hoping it will be a parent of 'cell death etc' terms @ValWood 

Tagging @KEHammond for any comments

**Comment by ValWood** [comment] 2019-06-21 15:10
Yes, I'm very convinced now this is the best way to do this.  We will be able to present the extensions on phenotypes only when they might be relevant which will improve the annotation specificity and consistency.

I look forward to figuring out more on Monday.

For effector, we might be able to make this an inferred parent. so we will run through that again.

**Comment by jseager7** [comment] 2019-09-19 09:16
Closing this issue now, since the request for a new annotation extension is finished and there hasn't been any further discussion.

**Closed by jseager7** 2019-09-19 09:16 UTC
Labels: PHI-Canto, needs testing
