### ISSUE TITLE
Single organism mode: phenotype links missing from gene page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1765] opened 2019-02-06 08:25 UTC
I have phenotypes configured but no link is present in single organism mode:

![single-user-gene-page-bug-1](https://user-images.githubusercontent.com/90474/52328747-914f7080-2a55-11e9-80ee-ce42a1dfb595.png)

**Comment by jseager7** [comment] 2019-02-06 10:08
I think this is because https://github.com/pombase/canto/pull/1663 didn't discriminate between single- and multi-organism modes. You could revert that commit and make the links display conditionally based on the mode, if you want a quick fix.

**Comment by jseager7** [comment] 2019-02-06 10:13
Personally, I've partly changed my mind about about removing the links after having done it, because when I've been adding single alleles to the session, I often find myself clicking the gene on the summary page instead of going to the genotype management view.

**Comment by kimrutherford** [comment] 2019-02-13 09:54
I agree.  Now that the host and pathogen ontologies are merged it might be OK again.  I've gone with your suggestion and revert that commit.

Maybe we should remove the "Multiple allele Phenotype" link?  Or perhaps move it further down the page and rename it to "Genotype management"?

**Comment by jseager7** [comment] 2019-02-13 12:29
> Or perhaps move it further down the page and rename it to "Genotype management"?

I think this is probably a better idea to avoid confusing any users that were used to the 'Multiple allele phenotype' link. We could add some extra text to clarify that the new link means the same thing as the old link.

**Comment by jseager7** [comment] 2019-02-20 10:23
I'm going to close this issue for now, since the issue itself is fixed. We can open new issues for any regressions that the revert created.

**Closed by jseager7** 2019-02-20 10:23 UTC
Labels: PHI-Canto, bug, high priority
