### ISSUE TITLE
new annotation type: complementation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#826] opened 2015-05-07 05:50 UTC
This is one of the curation types to migrate out of Artemis.
~The workflow here might also work for the Rothamstead host pathogen stuff as it requires being able to supply a ID from another organism in an extension.~

Priority, shortly after annotation extensions

Original comment by: ValWood

**Comment by ValWood** [comment] 2017-11-13 14:31
This has not been a prioirity as we can do in Artemis, but Rothamsted may also
 PHI Base may also to be able to curate inter-species complementation.

We postponed it originally because it requires the ability to specify a gene from another species, or the complementation of a phenotype in another species.

Rothamsted also mention  wt knockout + knock-in as a control to validate a deletion, but this is a bit different.

@CuzickA @Hammond-Kosack

**Comment by kimrutherford** [comment] 2017-11-21 11:03
Could you explain this one to me next time we chat on Skype?

**Comment by Antonialock** [comment] 2017-11-23 09:37
I would not annotate a WT knockout/in it doesn’t tell you anything about the biology just that the experimental technology worked as intended (eg you deleted the correct gene)

**Comment by ValWood** [comment] 2017-11-23 09:41
yep it's just a control. We don't annotate controls unless they are informative about the biology.
PHI base may have other reasons to record this...will check

**Comment by ValWood** [comment] 2018-04-19 15:32
1.
PomBase Curators discuss what is requires to migrate PomBase "interpsecies complementation type " from Artemis into Canto and describe in ticket

2. 
I think PHIBase is not complementation in the PomBase sense, ours is inter-species complementation experiments whereas PHIBase is  for  capturing experimental controls  for knockout, by complementation by the same gene.
@CuzickA  we don't capture these because we  expect that necessary checks to confirm the strain is deleted correctly have been handled by the review process, other than that it does not supply any more interesting biological detail.
However I think it is  probably possible to capture this if you really want to using  the current interface using "gene deletion + WT expression and normal phenotype?"
Could you check  i) if you really want to  capture this info  ii) if so is it possible at present iii) if not and you still want to capture, open a new ticket on this tracker to describe iv) add to PHI meeting agenda if any questions or any discussion required.

**Comment by ValWood** [comment] 2018-04-19 15:38
For 1, this is what we currently capture for "complementation"
https://curation.pombase.org/pombase-trac/wiki/Complementation
So perhaps we will enable multi-species mode for this!

**Comment by CuzickA** [comment] 2018-07-29 14:56
cross reference to https://github.com/PHI-base/curation/issues/7

Just re-reading and running though this issue again for PHI-Canto. 
1) As discussed above there doesn't really seem much point in curating the 'control' complementation expts.  **i.e mutant pathogen allele x WT pathogen gene** as this would take more time for the curators and should have been verified by the reviewers of the paper.
2) When there is a **mutant pathogen allele x altered original pathogen gene** expt it looks like this can be captured by creating a multi-allele genotype e.g.
https://github.com/PHI-base/curation/files/1703746/demo.pdf
3) We may also want inter-strain or inter-species complementation expts. Could this be adapted from https://curation.pombase.org/pombase-trac/wiki/Complementation ? How is this info currently captured for PomBase (not currently an option in Canto)?

**Comment by ValWood** [comment] 2018-07-29 16:32
At the moment we still do it in Artemis with a simple qualifier:

some exam[les on the cdc2 page (select complementation on menu)
https://www.pombase.org/gene/SPBC11B10.09

It's basically a very simple data structure.

Funcionally complemented by organism x, gene y
or
functionally complements organism x, gene y
or
does not complements organism x, gene y
or
is not functionally complemented by organismY + geneX

with qualifiers  full, partial


We should move this over to Canto fairly soon...
Kim has been doing "Expression" and we will do Complmentation after that. 

We may also want inter-strain or inter-species complementation expts. Could this be adapted from https://curation.pombase.org/pombase-trac/wiki/Complementation ? How is this info currently captured for PomBase (not currently an option in Canto)?

**Comment by kimrutherford** [comment] 2018-08-22 04:56
We had a discussion about this recently.  We think we might be able to handle this using the genotype/phenotype interface with some tweaks.  One possibility is to have a "Complementation mode" in the genotype interface which displays alleles / single allele genotypes from two organisms and forces the user to pick an allele from each species.  Probably a deletion in one organism and a wild type allele in the other?

**Comment by CuzickA** [comment] 2018-09-02 10:40
Sounds promising.
Would we annotate with similar terms mentioned above by Val (or with terms from phipo)? 
Do we need to distinguish between
1) a complementation phenotype seen in a pathogen (or host) only expt (eg restoration of normal hyphal growth on an agar plate) 
2) and a complementation phenotype seen in a disease formation expt (eg when a complemented pathogen is inoculated onto a host and normal pathogenicity is restored).

Would we need evidence codes/ conditions to capture this level of information? Or is this spilling too much into the phipo annotations. Perhaps we just want the does/does not complement terms as above.

**Comment by ValWood** [comment] 2018-09-03 12:01
When I am talking about "complementation" I'm only referring to the complementation of a gene in one species by another (is there  a more specific term for this ? exogenous complementation?)

For "endogenou"  complementation experiments, we do not capture these as we assume that authors have performed the necessary controls confirmed that the deletion is correct. 

Note that, In Canto the default assumption when we create a genotype is that the WT copy was removed. Therefore we only capture the WT copy explicitly if it is still present.
So you can capture endogenous   complementation genotypes already with  DeltaX WTX as a genotype.  If you need this routinely,  it might be an idea to create a stripped down  curation type of "endogenous complementation" later on, but in theory w you should be able to capture this already.

**Comment by mah11** [comment] 2019-04-02 12:51
tagging @gm119 @vmt25

**Comment by ValWood** [comment] 2019-06-04 12:11
closing this one. I believe the new mock up 

https://github.com/pombase/canto/issues/1915

covers all functionality/issues discussed here:

**Closed by ValWood** 2019-06-04 12:11 UTC
Labels: FlyBase, PHI-Canto, discuss, new data types, next, required for Artemis migration, sourceforge
