### ISSUE TITLE
pop up  form does not resolve well at larger screen size

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1479] opened 2018-05-29 21:53 UTC
I thought something had changed, then I realised I had my font  a point larger than the default.
Maybe it can be improved.

![someting changed](https://user-images.githubusercontent.com/7359272/40687590-17e80790-6393-11e8-9593-74c8d3aba5f1.jpg)

**Comment by kimrutherford** [comment] 2018-05-30 02:43
I don't know how to fix that one.  They only fix I know is to clip the overflowing elements, which also isn't great:

![annotation-dialog-crop-1](https://user-images.githubusercontent.com/90474/40695988-d06a5b0e-6417-11e8-99f0-f0a1f5043a51.png)

**Comment by kimrutherford** [comment] 2018-05-31 06:11
The problem is the same in Firefox.

**Comment by jseager7** [comment] 2018-05-31 09:36
I managed to replicate this problem by making my window narrow enough for the CSS media queries to trigger. I think I've tracked the problem to these rules in the main stylesheet:

https://github.com/pombase/canto/blob/0f046bc6fd463891fcfba615569e52b0f207bea1/root/static/css/style.css#L1385-L1388

The rules above are overriding the rules for `.form-control` in the bootstrap stylesheet:

https://github.com/pombase/canto/blob/0f046bc6fd463891fcfba615569e52b0f207bea1/root/static/css/bootstrap-3.3.7.css#L2549-L2551

If I remove that `width: auto` rule, or change it to `width: 100%`, then the popup scales correctly, even at very narrow screen sizes:

![smaller_modal](https://user-images.githubusercontent.com/37659591/40774767-609619c4-64be-11e8-9390-1ad6069d1c6f.png)

We still have the problem that on narrow screen sizes the experimental conditions get clipped because the drop-down isn't big enough to show them, and I'm not sure how to solve that yet.

- - -

@kimrutherford My main concern is that the commit (1f803cb) that made these changes to the stylesheet was doing it for a good reason, so if I change `width` for `.form-control` it could cause some unexpected side effects. Can you remember why the changes were made in the first place?

**Comment by kimrutherford** [comment] 2018-06-02 13:41
> Can you remember why the changes were made in the first place?

I'm not sure.  I'll have a deeper look and see if I can remember.  I may have been trying a fix a problem that we no longer have.

Would you be able to make a pull request with your preferred fix?  Removing "width: auto" probably makes sense.  I'll give it a test.

**Comment by jseager7** [comment] 2018-06-28 11:55
I think we forgot to close this after merging the pull request, so I'm closing it now.

**Closed by jseager7** 2018-06-28 11:55 UTC
Labels: user interface
