### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2076] opened 2019-10-17 10:09 UTC
curs/5564a30a271f4dce

Internal error
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: UNIQUE constraint failed: metadata.key [for Statement "INSERT INTO metadata ( key, value) VALUES ( ?, ? )"] at lib/Canto/Role/MetadataAccess.pm line 69

**Comment by ValWood** [comment] 2019-10-17 10:11
when I tried again it went. I got this  entering the session

**Comment by jseager7** [comment] 2019-10-17 10:53
Possibly related: #2077

**Comment by jseager7** [comment] 2019-10-17 11:08
This could potentially be bad if the database has failed to add some metadata to the session when it was supposed to, and now isn't receiving the trigger to attempt to store the data again on subsequent visits. Marking this as high priority just in case.

**Comment by kimrutherford** [comment] 2019-10-17 11:22
I think this might be caused by the server being very slow today.

> when I tried again it went. I got this entering the session

I'm think that if it works the second time the database will be fine.  I think we can close this and watch for it happening again.

**Closed** 2019-10-17 11:25 UTC
Labels: error
