### ISSUE TITLE
can't access metagenotype management from here

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2083] opened 2019-10-23 06:35 UTC
<img width="1172" alt="Screenshot 2019-10-23 at 07 34 33" src="https://user-images.githubusercontent.com/7359272/67364565-b47c6a80-f567-11e9-8c07-0bbbef683c28.png">

not sure why?

**Comment by kimrutherford** [comment] 2019-10-23 07:04
Possibly there are no host genotypes in the session?  If there isn't a mouse-over message about that on the "Metagenotype management" button there should be.

**Comment by ValWood** [comment] 2019-10-23 07:08
There are these:
https://canto.phi-base.org/curs/bd02fdb6831712ca/host_genotype_manage

**Comment by ValWood** [comment] 2019-10-23 07:09
and the button is "live" from here.

**Comment by kimrutherford** [comment] 2019-10-23 07:12
> There are these:
> https://canto.phi-base.org/curs/bd02fdb6831712ca/host_genotype_manage

I can't get to that session because I'm not an admin.

@jseager7 could you have a look at Val's issue when you have time?

**Comment by jseager7** [comment] 2019-10-23 09:00
I remember seeing this bug a while ago, but didn't have time to investigate since it was during a meeting. Thanks for reminding me.

**Comment by jseager7** [comment] 2019-10-24 11:54
I can't see this bug on the production server now that the session has been approved, and I can't reproduce the bug on my local environment either &ndash; I've tested in multiple curation session states (curating, reviewing, approving, etc.), all of them have the link enabled as it should be. My test session on the production server doesn't have any problems either. I guess we'll have to wait and see if this occurs again.

**Comment by kimrutherford** [comment] 2019-12-09 05:35
Val, if you see this again could you comment and let us know which session?

**Comment by kimrutherford** [comment] 2020-04-16 02:18
I think I'll close this and we can open a new issue if we see the problem again.

**Closed by kimrutherford** 2020-04-16 02:18 UTC
Labels: PHI-Canto, bug, cannot reproduce
