### ISSUE TITLE
Deleting genes problems

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1612] opened 2018-09-10 13:36 UTC
When a curator attempts to delete a gene from the Gene and host organism list page, there are some inconsistencies.

Firstly if the gene is used in a genotype the system allows the gene to be deleted, which takes the genotype with it

This is the same if a gene is annotated with a Go term

However, if the genotype is used in a metagenotype the deletion is prevented, but you get the following error:

![image](https://user-images.githubusercontent.com/1710907/45300612-c7201580-b506-11e8-821d-d851d67f4c23.png)

**Comment by kimrutherford** [comment] 2018-09-11 04:55
I've changed the gene confirmation page so that the checkboxes are disabled for genes that can't be deleted.  The reason is shown if you mouse-over the disabled checkbox:

![disable-gene-remove-1](https://user-images.githubusercontent.com/90474/45338694-99100380-b5e2-11e8-87c7-af49d8b5f765.png)

> if the genotype is used in a metagenotype the deletion is prevented, but you get the following error:

That's a separate problem.  I'm still working on that.

**Comment by kimrutherford** [comment] 2018-09-11 05:29
> if the genotype is used in a metagenotype the deletion is prevented, but you get the following error:

I can't reproduce that problem.  Could you check if you still see it?

**Comment by barnabynorman** [comment] 2018-09-11 09:42
@kimrutherford the error can be accessed here:

http://canto.phibase.org/curs/a47d6205d86a1936/edit_genes?gene-select=1&submit=Remove+selected

The error should not happen now as you have disabled the checkbox!

**Comment by kimrutherford** [comment] 2018-09-11 09:51
OK, thanks.  I'll close this one and we can open new issues for problems.

**Closed by kimrutherford** 2018-09-11 09:51 UTC
Labels: bug
