### ISSUE TITLE
PHI canto edit window slow to appear

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2297] opened 2020-06-08 10:49 UTC
Recently, (we think since me and @CuzickA  chatted last Monday).

Loading the "edit" window has become much slower. We only see the very top of the window initially, and then after sometimes quite a number of seconds), the existing data appears.

Did something change?

**Comment by jseager7** [comment] 2020-06-08 10:51
@ValWood Is this the Edit link on annotation tables on the summary page?

**Comment by jseager7** [comment] 2020-06-08 11:00
It doesn't seem particularly slow to me, based on the test session on our production server. I get a delay of about half a second before all the data appears.

As far as I know, the only major thing that changed recently was an upgrade to the Docker container that we use to run Canto, but that would probably affect PomBase too. 

I can only speculate, but it's possible that the delay could be due to general degradation of connection speed (maybe due to the high levels of internet traffic from countries in lockdown), which can't really be helped. Otherwise, maybe the modal loads slowly when trying to process a lot of existing features (genes, genotypes, etc.) or annotations.

@kimrutherford Is the slowdown on this modal likely to be caused by network performance or client-side performance? Does it need to fetch a lot of data from the server?

**Comment by ValWood** [comment] 2020-06-08 12:58
Yes that's the place. I haven't noticed the same slowness anywhere else today, ain't was the same for myself and @CuzickA  at different locations.

**Comment by jseager7** [comment] 2020-06-08 13:00
> I haven't noticed the same slowness anywhere else today, ain't was the same for myself and @CuzickA at different locations.

That would suggest it was a temporary problem with our hosting provider. I did notice some slowdown about a week ago, but assumed it was just due to heavy internet traffic.

Should we close this issue?

**Comment by ValWood** [comment] 2020-06-08 13:09
OK!

**Closed** 2020-06-08 13:10 UTC
Labels: PHI-Canto, cannot reproduce, performance
