### ISSUE TITLE
Exception after replacing default phenotype annotation type

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1476] opened 2018-05-29 13:03 UTC
I added new phenotype annotation types from PHIPO into `canto_deploy.yaml`, and removed the default `phenotype` annotation type, but now attempting to annotate a genotype using the genotype management workflow throws an exception:

`Internal error: Caught exception in Canto::Controller::Curs->start_annotation "no category configured for annotation type: phenotype"`

![no_phenotype_configured](https://user-images.githubusercontent.com/37659591/40660087-f3d8579c-6347-11e8-8ea1-d3e2a670ebe2.PNG)

This problem doesn't occur when annotating genes, since all the annotation types are listed by default:

![phipo_annotation_list](https://user-images.githubusercontent.com/37659591/40660468-fe14ee0e-6348-11e8-9503-55179701a031.PNG)

**Comment by kimrutherford** [comment] 2018-05-30 01:28
I think the problem is that the ontology/annotation_type name is hard coded as "phenotype" in the genotype page.

Here's the code:
   https://github.com/pombase/canto/blob/master/root/static/ng_templates/genotype_list_row_links.html

Near the top we have:

```javascript
   ... + genotypeId + '/start/phenotype/'
```

The "phenotype" should change depending on the type of genotype.  It should be "host phenotype", "pathogen phenotype" etc.

This problem is related to #1471.

**Comment by kimrutherford** [comment] 2018-08-23 05:31
This should be fixed now due to: https://github.com/pombase/canto/issues/1471#issuecomment-415285198

**Closed by kimrutherford** 2018-08-23 05:31 UTC
Labels: PHI-Canto, annotation, error
