### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1271] opened 2016-10-17 10:00 UTC
Keep meaning to submit this. Quite a few special characters are a bit screwy. This problem appeared when some recent character problems were fixed, I think .....

![special charactars](https://cloud.githubusercontent.com/assets/7359272/19433495/e493dc26-9458-11e6-8d2b-73c599bbb814.jpg)

**Comment by kimrutherford** [comment] 2016-10-19 11:26
This is a bit frustrating as it works fine on my laptop.  I'll dig deeper tomorrow.

![screenshot 2016-10-20 00 25 03](https://cloud.githubusercontent.com/assets/90474/19517094/aea119f8-965b-11e6-9030-7c9e1f6d4cd2.png)

**Comment by ValWood** [comment] 2016-10-19 11:39
Weird...

**Comment by Antonialock** [comment] 2016-10-27 09:33
I see this using both firefox and chrome
https://curation.pombase.org/pombe/view/object/person/98?model=track

![screen shot 2016-10-27 at 10 33 06](https://cloud.githubusercontent.com/assets/12727506/19762174/d2aa74fe-9c30-11e6-969e-ed693fb6250c.png)

![screen shot 2016-10-27 at 10 32 14](https://cloud.githubusercontent.com/assets/12727506/19762178/d7fef5a6-9c30-11e6-8413-b02a1ef23499.png)

**Comment by ValWood** [comment] 2016-11-01 09:40
quite a lot of these in sessions I am waiting to send out. I won't send them until this is fixed. Not super urgent but  fairly high priority
![funny characters](https://cloud.githubusercontent.com/assets/7359272/19885563/289a0020-a017-11e6-9b69-761f887e4018.jpg)

**Comment by kimrutherford** [comment] 2016-11-01 09:58
OK, I'll have another go tomorrow.  I was stumped about it last week but I'll have a fresh look.  I still can't reproduce the problem on Canto on my laptop.

**Comment by kimrutherford** [comment] 2016-11-01 23:10
I think I've fixed this now.  Everything seems OK in the database but it was being mangled when read from the database.  I wasn't using the right flag in the right place in the code.  I'll close this now but please reopen if you stop any problems.

**Closed by kimrutherford** 2016-11-01 23:10 UTC
Labels: bug, high priority, next

**Comment by ValWood** [comment] 2016-11-02 06:07
perfect now ;)
