### ISSUE TITLE
Cannot differentiate same gene from different species  when selecting genes for extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2101] opened 2019-11-06 15:37 UTC
See:

<img width="703" alt="Screenshot 2019-11-06 at 12 51 27" src="https://user-images.githubusercontent.com/7359272/68312667-4e393100-00ab-11ea-9801-ac984e479161.png">

**Comment by ValWood** [comment] 2019-11-06 15:38
Note that, even after you selected you can't check you have the correct one either...

**Comment by kimrutherford** [comment] 2019-11-06 19:40
Do you have the two UniProt IDs handy so I can reproduce the problem locally?

**Comment by ValWood** [comment] 2019-11-06 20:55
I1S9X9
and
Q51WZ9

in 9133cb6f3978f78d/edit_genes

**Comment by kimrutherford** [comment] 2019-11-11 01:50
Do we need to add the organism after the gene name?

![annotation-edit-gene-1](https://user-images.githubusercontent.com/90474/68555421-9339da80-0492-11ea-90df-597a77c144ea.png)

**Comment by jseager7** [comment] 2019-11-11 10:43
@ValWood are you specifically talking about the gene drop-down on the annotation extension dialog?

![image](https://user-images.githubusercontent.com/37659591/68580086-8787ed00-046d-11ea-9e2b-a0197fec0a35.png)

Because the image in your initial comment shows the gene drop down on the GO annotation dialog:

![image](https://user-images.githubusercontent.com/37659591/68580156-ad14f680-046d-11ea-85cb-8c74e724ff43.png)

It looks like the GO annotation drop-down is showing genes for all organisms, rather than the organism being annotated (this seems a bit counter-intuitive to me, in the example above I'd expect to only see the genes TRI5 and URA7, since these are the only genes in the session for _F. graminearum_). Not sure if we have an issue open for this already.

As for the annotation extensions, most of the extensions that involve a gene ID in PHI-Canto are related to an assay (assayed_using) &ndash; in this case, does it ever make sense to assay using a gene from a different organism? Is that why you needed to select a gene from another organism?

**Comment by ValWood** [comment] 2019-11-11 11:12
yes you are right @jseager7. Showing only the genes for the organism being annotated would fix this issue.

**Comment by jseager7** [comment] 2019-11-11 12:40
@kimrutherford It sounds like this issue could require changes to the annotation extension configuration syntax (unless we can handle this with further processing on the front-end).

Currently, if you use the 'GeneID' range on an extension, Canto shows all the genes in the session (for every organism), but it sounds like we want to only see the genes for the 'current' organism (that is, the one being annotated with a phenotype term).

I think we either need:

- a new option in the extension configuration (e.g. OrganismGeneID) that filters the genes returned to only the organism being annotated; or

- extra processing on the front-end to take the list of genes returned by the annotation extension web service (?) and filter them by organism.

Which do you think is more feasible?

**Comment by kimrutherford** [comment] 2019-11-11 23:36
> Which do you think is more feasible?

I think plan two is best - filter the genes in the extension component.

**Comment by jseager7** [comment] 2019-11-13 13:46
It was easier to display the organism names after the genes (as suggested here https://github.com/pombase/canto/issues/2101#issuecomment-552262132), so I've done that for now. The change still needs testing to make sure the organism names don't show when Canto is in single organism mode.

Long-term I'm hoping to make it so that the gene drop-down only shows genes from the organism currently being annotated, because it looks like for a lot of annotation extensions it's not valid to pick a gene from another organism. For the cases where users _do_ need to pick a gene from a different organism (possibly needed for physical / genetic interactions in PHI-Canto), users will be able to select an organism to before selecting the gene. Unless people prefer the existing solution of just showing all the genes with the organism name appended.

**Comment by jseager7** [comment] 2019-12-10 13:11
I'm closing this for now since the issue itself is fixed. If we decide to filter the genes by organism everywhere, then that belongs in a new issue.

**Closed by jseager7** 2019-12-10 13:11 UTC
Labels: PHI-Canto
