### ISSUE TITLE
Add ability to add 'missed' alleles without overwriting existing curation

### ISSUE THREAD

**Issue by gm119** [pombase/canto#2248] opened 2020-03-10 09:46 UTC
The FlyBase Canto model imports alleles/aberrations for each publication (curated external to Canto by FlyBase 'genetic reagent' curators) via a json input file and then phenotypes etc. are added to those existing alleles/aberrations (or genotypes made from them).

However, occasionally the genetic reagent curation of alleles/aberrations misses an allele (.e.g. if only mentioned fleetingly in text/buried in a figure) and this is only discovered upon phenotype curation.

Currently when this happens, the phenotype curators ask the genetic reagent curators to make the missing entries for them, and then once the missing entries have been attributed to the paper, they can then add the relevant phenotypes

So we would like to have something like this in Canto, whereby the json could 'add' missing alleles/aberrations, without erasing any existing annotations to 'in-progress' records and without creating a new session (I think the latter is true ?).

On the VC, we discussed that the import code could check whether any change to an allele/aberration had been made in Canto for that publication, and if there was a change it would not try to import anything, but if there was no change in canto (which should include if the allele/aberration was not already attached to the publication in canto), it would import the information into the existing session so that it would become available for the phenotype curators to use for that publication

**Comment by vmt25** [comment] 2020-03-10 18:25
> and without creating a new session (I think the latter is true ?).

Currently it creates a new session if there is already a session for that publication regardless of the status (in progress, approved). This should not happen and I created a ticket for it #2251.

**Comment by kimrutherford** [comment] 2020-03-31 05:19
> check whether any change to an allele/aberration had been made in Canto for
> that publication

I think that's OK because we don't change alleles once they are in Canto.  So we should be able to check for alleles that aren't already loaded and then add them if missing.  Am I understanding that correctly?

**Comment by vmt25** [comment] 2020-05-05 14:19
From discussion at today's VC with Kim and Gillian (plus a few other extra bits to take into consideration):

For publications already present, the loader should compare the new gene list and the allele list for a publication - which should be relatively simple because of FlyBase's use of unique IDs)

Addition of new genes/alleles (i.e. present on the import file but not yet on Canto) - do by default for all sessions

Deletion of genes/alleles (i.e. present in Canto but not in the import file):
a) for all 'new sessions', do by default 
b) for active sessions:
(i) do if there is no annotation for that gene/allele, except if there is an allele created in that session (e.g. temporary allele - see #2282)
(ii) do not delete but create a warning if there are already some annotations for allele / gene; not sure how the warning should look like: log on import plus warning within the session?

**Comment by kimrutherford** [comment] 2020-06-21 00:46
> Addition of new genes/alleles
> 
> Deletion of genes/alleles

I've had a first attempt at implementing the addition of missing genes and alleles.  I'd like to do some testing with real data next.

I haven't implemented the deletion of genes/alleles yet because.  Deletion is riskier than addition so I wanted to get the addition of genes/alleles working first.  As a work-around, the extra genes and alleles can be removed using the Canto web interface.

**Comment by kimrutherford** [comment] 2020-06-25 03:36
As discussed on the call, I'll test this next time there is a new JSON file for importing.

**Comment by vmt25** [comment] 2020-07-08 18:47
Please see the repository https://github.com/vmt25/Fly-Canto-updates-Publications-and-config-files- and the associated email thread 'Repository with publication import json file and extension_config.tsv'

**Comment by kimrutherford** [comment] 2020-08-24 21:28
Hi Vitor.

Sorry it has taken me so long to get back to this issue.  Could you remind me: should I test loading the new JSON file ("import_publications_06-07-2020.json") in your repository?

I can't find the email thread you mention:

> associated email thread 'Repository with publication import json file and extension_config.tsv'

Would you mind forwarding it to me?  Thanks!

**Comment by vmt25** [comment] 2020-11-10 21:15
From our conversation Skype chat:
a) adding missed genes/alleles seems to have worked fine on your test.
b) updating/removing out-dated alleles would be useful
        Gene/allele renames - objects keep the FlyBase id (FGgn/FBal)
        Gene merges (two or more genes are found to the same gene) - a new ID/object is made; the old ids of the merged genes become secondary ids of the new object.
        Gene changes species - a new ID/object is made.
I will send Kim a few examples by email.

For genes/alleles that stop being linked with the publication
a) delete if they have no associated annotation in Canto
b) issue a warning if they already have annotations in Canto

**Comment by kimrutherford** [comment] 2020-11-10 22:30
> Gene merges (two or more genes are found to the same gene) - a new ID/object is made; the old ids of the merged genes become secondary ids of the new object.

@gm119 to make this easier, would be be possible to include the secondary IDs in the JSON input file somehow?  Or maybe they could be queried from the synonym table in Chado?

> Gene changes species - a new ID/object is made.

Is the old ID kept as a secondary ID if that happens?

> For genes/alleles that stop being linked with the publication
> ...
> b) issue a warning if they already have annotations in Canto - do not delete gene or annotations

Is that still the case if a gene was merged and there annotations that use the old ID?  Or should the annotations be updated to use the new ID?

**Comment by gm119** [comment] 2020-11-11 14:50
1. 

> Gene merges (two or more genes are found to the same gene) - a new ID/object is made; the old ids of the merged genes become secondary ids of the new object.

the secondary IDs are in chado, but not in the synonym table. There will be an entry in the feature_dbxref table (with is_current = f) that links the current valid feature (feature_id) with a dbxref entry (dbxref_id) and in the dbxref table the corresponding entry (with the same dbxref_id) will have the FBal/FBgn in the 'accession' and db will be '4' (this is the db for 'FlyBase'). If you have a specific example I can paste in the relevant sql/results to show that more clearly (!)



2.



>     Gene changes species - a new ID/object is made.
> 
> Is the old ID kept as a secondary ID if that happens?

if a gene (or allele) changes species, then what actually happens is the same as the gene merge in 1., so yes, the old ID is kept as a secondary ID, in the feature_dbxref as above

3. 


```

    For genes/alleles that stop being linked with the publication
    ...
    b) issue a warning if they already have annotations in Canto - do not delete gene or annotations

Is that still the case if a gene was merged and there annotations that use the old ID? Or should the annotations be updated to use the new ID?
```
I think that the answer is that if there is a merge and canto contains annotations (which use the old FBid) then the canto annotations should be updated to use the new ID.


I'm not sure from the issue thread what will trigger Canto to 'know' that a gene merge has happened - is this something that will happen without a Canto json input file, but will happen when the underlying chado changes ? I think its probably the latter, so I guess Canto will have a list of FBgn that are no longer valid in chado ('old FBgn') - in that case, if you are able to use feature_dbxref to query for the new current FBgn, I'd recommend checking that the 'old FBgn' is only listed as a secondary ID under a single currently valid FBgn (if a gene is split the old FBgn would end up under multiple current FBgn).

If I haven't provided the necessary info to help then perhaps splitting the various issues in this ticket into separate git issues might help (I am getting confused as to which aspect will require an input json file to trigger the change and which will happen without an input json file as you can probably tell from the above paragraph!)

**Comment by kimrutherford** [comment] 2020-11-16 10:53
Hi Gillian.  Thanks for that.  I think we can cope with all the cases but it would help a lot if the input JSON file could include the old FBid.  Would you be able to add them?

The current `genes` section of the input file looks like:
```json
 "genes" : [
    "FBgn0000120",
    "FBgn0000121",
    "FBgn0014445"
 ]
``` 

Perhaps we could change it to something like:

```json
 "genes" : {
    "FBgn0000120": {
       "old_uniquenames": [
          "FBgn01234567",
          "FBgn06543210"
       ]
    },
    "FBgn0000121": {
    },
    "FBgn0014445": {
    }
 }
```

or if it's easier:

```json
 "genes" : [
    {
       "uniquename": "FBgn0000120",
       "old_uniquenames": [
          "FBgn01234567",
          "FBgn06543210"
       ]
    },
    {
       "uniquename": "FBgn0000121"
    },
    {
       "uniquename": "FBgn0014445"
    }
 ]
```

The `"old_uniquenames":` field could be `[]` or `null` in the case where there are no old FBgn IDs if that's simpler.

And we don't need to name it "old_uniquenames".  It could be anything.

Maybe "uniquename" should be something like "primary_identifier"?  "uniquename" is a bit Chado specific.

I'm happy to have a quick Skype about this at some point if that would help.

**Comment by gm119** [comment] 2020-11-16 12:05
>  I think we can cope with all the cases but it would help a lot if the input JSON file could include the old FBid. Would you be able to add them?

I should be able to, but might need your help with the sql queries ! I'll have a think and get back to you with any questions  - probably won't be till the end of the week, as we're nearing a release deadline (thursday) which is always quite busy!

**Comment by kimrutherford** [comment] 2020-11-18 11:02
> I should be able to,

Thanks!

>  but might need your help with the sql queries

I had a go at a query.  This seemed to work:

```sql
SELECT DISTINCT uniquename  AS new_gene_uniquename,
                f.name      AS new_gene_name,
                x.accession AS old_gene_uniquename
FROM feature f
JOIN cvterm t            ON f.type_id = t.cvterm_id
JOIN feature_dbxref fdbx ON f.feature_id = fdbx.feature_id
JOIN dbxref x            ON fdbx.dbxref_id = x.dbxref_id
WHERE f.uniquename = 'FBgn0287720'
  AND fdbx.is_current = 'f'
  AND x.accession IN
    (SELECT uniquename
     FROM  feature obsolete_feature
     JOIN  cvterm obsolete_feature_type ON obsolete_feature.type_id = obsolete_feature_type.cvterm_id
     WHERE obsolete_feature_type.name = 'gene');
```

**Comment by kimrutherford** [comment] 2020-11-27 11:15
From the Skype call:

  - Gillian will add a secondary_identifiers field for genes and alleles.  
  - Kim will start implementing the changes for loading

Implementation notes for Kim:

 - if the publication in the JSON file isn't in Canto, load all the alleles and genes

 - if a session already exists for a publication, the loader will need to:

   - check for genes and alleles that are in the input but not in Canto
   - if any of the secondary IDs of the new genes or alleles match an existing gene or allele, update the ID in Canto to the primary_identifier
   - but:
     - warn about cases where there are two new genes or alleles that have a secondary ID in common and the secondary ID is in use in Canto
     - this is caused by a gene/allele split in Chado and isn't common
     - don't change the Canto gene/allele in this case

   - after processing all the new genes and alleles:
      - warn about gene and allele IDs that are in the Canto database but aren't in input file
      - this will catch IDs that are now obsolete or that aren't associated with the publication anymore

I think we decided to go for this style of input:

```json
"genes" : {
    "FBgn0000120": {
       "secondary_identifiers": [
          "FBgn01234567",
          "FBgn06543210"
       ]
    },
    "FBgn0000121": {
    },
    "FBgn0014445": {
    }
 }
```

and for alleles:

```json
     "alleles" : {
         "FBab0045200" : {
            "comment" : null,
            "name" : "Df(3L)BSC386",
            "type" : "aberration",
            "secondary_identifiers": [ ... ]
         },
         "FBal0141341" : {
            "comment" : "BDSC number BL7012. gm190426.",
            "gene" : "FBgn0021796",
            "name" : "Tor[WT.UAS.Tag:FLAG]",
            "synonyms" : [
               "UAS-TOR"
            ],
            "type" : "other",
            "secondary_identifiers": [ ... ]
         }
    }
```

**Comment by gm119** [comment] 2020-11-27 11:51
style of input looks good to me.

**Comment by gm119** [comment] 2020-11-27 15:34
I have implemented the changes to make the input above.
If a gene has no secondary_identifiers it looks like the sample json above.

For alleles, it looks like this:



      "alleles" : {
         "FBal0321293" : {
            "comment" : null,
            "gene" : "FBgn0284334",
            "name" : "Spyo\\Cas9[nos.cPa]",
            "secondary_identifiers" : [
               "FBal0320679",
               "FBal0294141"
            ],
            "synonyms" : [
               "nos-Cas9"
            ],
            "type" : "accessory"
         },
         "FBal0325365" : {
            "comment" : null,
            "gene" : "FBgn0004644",
            "name" : "hh[TOE.GS00191]",
            "synonyms" : [
               "hh sgRNA"
            ],
            "type" : "other"
         },
 
      },

i.e. if there are no secondary_identifiers for the allele, there is no "secondary_identifiers"  item in the json.
Would you prefer it if it had

"secondary_identifiers" : []

instead when there are no secondary_identifier ? just let me know !

**Comment by kimrutherford** [comment] 2020-11-27 22:16
That looks great.  Thanks for the quick work!

> if there are no secondary_identifiers for the allele, there is no "secondary_identifiers" item in the json.

That's no problem.  Thanks.

**Comment by kimrutherford** [comment] 2020-12-03 01:04
I'm implementing this now.  I think it will work out OK.

Can allele names or types change?  For example could the allele name change if alleles are merged?  It makes a bit of a difference to the implementation of the allele loading bit.

**Comment by gm119** [comment] 2020-12-03 09:47
> Can allele names or types change? For example could the allele name change if alleles are merged?

1. allele names
yes, allele names can change if alleles are merged, i.e. it is possible to merge allele name A + allele B and call the merged thing allele C   (it is also possible to merge alleles and 'keep' one of the original names for the merged thing, so both possibilities can happen.

2. allele type
hmm. I think that it is formally possible that an allele type might change, for example, it could change from 'other' to 'accessory' if the original curation had forgotten to mark the parent gene as being used as an experimental tool. So although this will  be rare, yes I think it could occur.

**Comment by kimrutherford** [comment] 2020-12-04 00:23
Thanks Gillian.  I'll make the fixes needed to support allele re-names and type changes.

**Comment by kimrutherford** [comment] 2020-12-04 04:11
> I'll make the fixes needed to support allele re-names and type changes.

I've made those changes.

Most of the code is done now except for:

  -  warn about cases where there are two new genes or alleles that have a secondary ID in common and the secondary ID is in use in Canto
  -  warn about gene and allele IDs that are in the Canto database but aren't in input file

I'll do that next.

**Comment by kimrutherford** [comment] 2020-12-04 10:40
>  Most of the code is done now except for:
> 
>  -   warn about cases where there are two new genes or alleles that have a secondary ID in common and the secondary ID is in use in Canto
> -   warn about gene and allele IDs that are in the Canto database but aren't in input file

All done and ready for testing.

**Comment by gm119** [comment] 2021-01-22 14:41
sample json (ticket_2248.json) sent to kim

**Comment by kimrutherford** [comment] 2021-02-05 09:05
From an email chat with @gm119: need to handle the case when the gene of an allele changes but the other details stay the same.

Gillian's example from email:

--------

before:

```json
          "FBal0346072" : {
             "comment" : "Integration into the attp40 site, so used P{} 
ends and made a matching insertion. al190221.",
             "gene" : "FBgn0037714",
             "name" : "CG9396[UAS.cSa]",
             "synonyms" : [
                "UAS-MPC1-MPC2"
             ],
             "type" : "other"
          }
```

after:

```json
          "FBal0346072" : {
             "comment" : "Correspondence from C. Thummel (via K. Cook) 
established that the 'MPC2' sequence in the 'UAS-MPC1-MPC2' construct 
(FBtp0132931) is CG9399 and not CG9396, so moved allele and renamed 
construct and insertion accordingly. gm210121. Integration into the 
attp40 site, so used P{} ends and made a matching insertion. al190221.",
             "gene" : "FBgn0037715",
             "name" : "CG9399[UAS.cSa]",
             "synonyms" : [
                "UAS-MPC1-MPC2"
             ],
```

**Comment by kimrutherford** [comment] 2021-02-09 06:29
> need to handle the case when the gene of an allele changes but the other details stay the same.

I've fixed that now so the gene of the allele in Canto gets updated.  The output from loading `FBrf0236523_after_changes.json` is now:

```
  updating existing session 5629dfe8180da2c8 for PMID:28812582
  adding new gene to existing session: FBgn0037715
  gene for "FBal0346072" changed from "FBgn0037714 to "FBgn0037715"
  adding new allele to existing session: FBal0236142
  gene FBgn0037714 is the Canto database is not in the JSON input for session: 5629dfe8180da2c8
  allele FBal0238310 is the Canto database is not in the JSON input for session: 5629dfe8180da2c8
  created 0 sessions
  updated 1 sessions
```

We might not need all this output once the JSON loader is well tested but for now it's helpful for debugging problems.

I think the last major thing to fix is this:                                                                                                            

```
  gene FBgn0037714 is the Canto database is not in the JSON input for session: 5629dfe8180da2c8
  allele FBal0238310 is the Canto database is not in the JSON input for session: 5629dfe8180da2c8
```

The loading code needs to remove the genes and alleles from the Canto session that are gone from the JSON.   And also warn if any of the genes to be removed have annotation.

**Comment by gm119** [comment] 2021-02-09 09:43
excellent - I like the warnings, really clear what is going on

**Comment by kimrutherford** [comment] 2021-02-10 10:39
> The loading code needs to remove the genes and alleles from the Canto session that are gone from the JSON.

I think that's implemented now but I'm going to do more testing tomorrow.

**Comment by kimrutherford** [comment] 2021-02-11 04:15
Everything looks OK after more testing so I think the loading code is ready for the next FlyBase Chado release.

**Comment by kimrutherford** [comment] 2021-02-18 02:07
Gillian sent two more test files, with an example of an allele ID change.  A before and after file.  Loading the "before" JSON file reported no changes (correctly).  Loading the "after" JSON file mostly worked except that a change of allele note/comment was ignore by the loading code.  That's fixed now.

**Comment by kimrutherford** [comment] 2021-03-18 02:30
> Everything looks OK after more testing so I think the loading code is ready for the next FlyBase Chado release.

I think we can close this now.  There was a problem with the session curators being reset to "FlyBase Admin" but that's fixed now.

**Closed by kimrutherford** 2021-03-18 02:30 UTC
Labels: FlyBase, high priority, next
