### ISSUE TITLE
Duplicated text for some evidence codes in edit option

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1995] opened 2019-08-05 12:19 UTC
![image](https://user-images.githubusercontent.com/11753634/62463842-f83eaf80-b782-11e9-820c-168742d52e1f.png)

Displays alright in the annotation
![image](https://user-images.githubusercontent.com/11753634/62463966-51a6de80-b783-11e9-91e3-3f5b3b188bcc.png)

@jseager7 I have just noticed this. Please could you take a look.

**Comment by jseager7** [comment] 2019-08-05 14:39
I've taken a look at the `canto_deploy` file on the server, and the duplication isn't present there, so this must be a bug with Canto's code.

@kimrutherford Is it possible this occurred due to the changes needed to support genotype-to-genotype genetic interactions? I seem to remember you saying it involved changes to the edit modal.

**Comment by jseager7** [comment] 2019-08-06 09:30
@kimrutherford I've figured this out now. The bug is due to unescaped special characters in a dynamically generated regular expression. The offending function is `getDisplayCode()` in the `annotationEvidence` controller:

```js
$scope.getDisplayCode = function (code) {
  if ($scope.evidenceTypes) {
    var name = $scope.evidenceTypes[code].name;
    if (name) {
      if (name.match('^' + code)) {
        return name;
      }
      return name + ' (' + code + ')';
    }
  }

  return code;
};
```

The problem is because the regular expression is constructed simply by concatenating `code` with no further processing (such as escaping):
```
if (name.match('^' + code)) {
...
```
Meaning when the evidence code happens to contain regex special characters (and PHI-base's list does), you get this pattern:
```
/^Macroscopic observation (quantitative observation)/
```
Which, because the brackets are parsed as a match group and not literal brackets, actually tries to match this:
```
/^Macroscopic observation quantitative observation/
```
That doesn't match the text, so the function returns `name` followed by `code` in brackets, which in this case is just the same text twice:

> Macroscopic observation (quantitative observation) (Macroscopic observation (quantitative observation))

If we have to use regex, then I think we can only really solve this by escaping regex special characters in `code` before matching against it. I've managed to find a function that will do this (see below), but maybe there could be a different way to solve this? Perhaps we could match without regular expressions, or use a lookup table that links abbreviations to their expanded names?

- - -
```js
function escapeRegExp(string) {
  // $& means the whole matched string
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); 
}
```

**Comment by kimrutherford** [comment] 2019-08-09 02:05
Perhaps we could change:
```js
if (name.match('^' + code)) {
```
to:
```js
if (name.startsWith(code)) {
```

I think that's the same.

**Comment by jseager7** [comment] 2019-08-12 09:13
Yes, those two functions should be the same for matching behaviour, and we don't have to worry about any escaping when using `String.prototype.startsWith()`, so I support changing to that.

**Comment by jseager7** [comment] 2019-08-12 11:40
@kimrutherford I've just pushed a fix for this issue. I've checked how it looks in the physical / genetic interaction dialog and I think everything seems fine there (see image below). Feel free to close this issue after you've tested further, if you need to &ndash; otherwise you can just close now.

![image](https://user-images.githubusercontent.com/37659591/62862607-347f8c00-bcfe-11e9-9362-099c8351c9dc.png)

**Comment by kimrutherford** [comment] 2019-08-12 22:27
Thanks James.  It works for me.

**Closed by kimrutherford** 2019-08-12 22:27 UTC
Labels: PHI-Canto, bug
