### ISSUE TITLE
multi-species genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2088] opened 2019-10-25 11:37 UTC
Looks like this before you have added any genotypes.

Does this need a way to  tell people that they first need to curate pathogen and host genotypes

<img width="1074" alt="Screenshot 2019-10-25 at 12 35 43" src="https://user-images.githubusercontent.com/7359272/67568467-387b5180-f724-11e9-85bf-85644d14c71f.png">

**Comment by jseager7** [comment] 2019-11-07 10:40
This is more or less a duplicate of #1678. However, that issue seems to have been neglected for a long time. I could take another look at it, but it's possibly better suited for @kimrutherford since it involves Perl code.

**Comment by kimrutherford** [comment] 2019-11-07 11:07
>  I could take another look at it, but it's possibly better suited for @kimrutherford since it involves
> Perl code.

I started looking at it yesterday but got distracted.  I'll work on it.

**Comment by kimrutherford** [comment] 2019-11-11 02:08
I think this is done now.

**Closed by kimrutherford** 2019-11-11 02:08 UTC
