### ISSUE TITLE
fiendish extension configuration scenario - if this ancestor but not that descendant

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1021] opened 2015-11-02 14:54 UTC
Fortunately, nothing needs to be done now, and possibly not for quite a while. I'm just getting this down now in case it becomes an issue some day.

Up until the most recent commit, the FYPO extension config file had entries for both FYPO:0000682 and FYPO:0004916 (which is the only is_a child of FYPO:0000682 at present). That was making too many extension option linkies appear, so for now I've deleted FYPO:0000682 from the config file.

If we ever add terms for phenotypes affecting regulation of other functions (binding, transporter activity, etc.) we might have to do something scarily clever with extension configuration, of the "use this if it's FYPO:0000682 but not FYPO:0004916" persuasion. Should that scary vision become reality, we can discuss what would need to be done more specifically.

FYPO:0000682 abnormal regulation of molecular function
is_a FYPO:0004916 abnormal regulation of catalytic activity

**Comment by ValWood** [comment] 2015-11-23 13:42
Yup.
For now if I saw 2 extensions appear I refined the config so that only the more specific one is required....
This is an alternative option, we might want  it for cases where refinement is just too difficult

**Comment by mah11** [comment] 2016-05-03 16:15
Note (as much to self as anyone else): we'll also want to use this to ensure that FYPO "abolished" terms don't offer the expressivity option. Might need to add one or more "abolished process|function" grouping terms to use in the config. See https://github.com/pombase/fypo/issues/2652 (closed because there's nothing to do it FYPO itself, and the config update has to wait for this ticket).

**Comment by kimrutherford** [comment] 2016-06-13 04:18
I think this is a duplicate of #1040.

**Closed by kimrutherford** 2016-06-13 04:18 UTC
Labels: extension interface, ontology_subsets
