### ISSUE TITLE
session with duplicate alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2682] opened 2022-12-12 15:23 UTC
2a8be2bb0239204b

<img width="792" alt="Screenshot 2022-12-12 at 15 20 59" src="https://user-images.githubusercontent.com/7359272/207083679-5073a90e-364a-4d71-8089-232f230f0043.png">

...and I can't delete them...

**Comment by ValWood** [comment] 2022-12-12 15:30
same here
fe7a0f32d4e76d5d/
<img width="443" alt="Screenshot 2022-12-12 at 15 29 30" src="https://user-images.githubusercontent.com/7359272/207085514-26236a04-481c-4397-8e3c-89bdb57270ec.png">

i deleted both. Both reappeared?

**Comment by ValWood** [comment] 2022-12-12 16:21
more duplicates that I can't delete. Even triplicates.

Are we  duplicating instead of deleting?


<img width="583" alt="Screenshot 2022-12-12 at 16 20 30" src="https://user-images.githubusercontent.com/7359272/207097944-5e105b8f-76b0-4fac-aefc-60b226124c67.png">

**Comment by kimrutherford** [comment] 2022-12-12 23:32
> ...and I can't delete them...

What error do you get?

> Are we duplicating instead of deleting?

Do you get more copies when you try to delete them?

**Comment by ValWood** [comment] 2022-12-13 10:55
I think so. We can troubleshoot  later

**Comment by ValWood** [comment] 2022-12-13 12:29
Is it this issue?
https://github.com/pombase/canto/issues/2642

**Comment by ValWood** [comment] 2022-12-13 18:28
they are appearing all over! ;)

curs/393d0a5aae35d3ac/genotype_manage

**Comment by kimrutherford** [comment] 2022-12-14 00:33
Do you have a way to reproduce the problem?  I can't see anything odd about these sessions except for the duplicates.

**Comment by ValWood** [comment] 2022-12-20 13:00
ping me if you are online any time before the New Year, if I am around we can troubleshoot this.

**Comment by kimrutherford** [comment] 2023-01-17 01:08
I haven't been able to reproduce this problem on my desktop.

**Comment by ValWood** [comment] 2023-01-19 08:59
It's clearly  something to do with them being part of multi-gene genotypes.
I have sometimes deleted single gene genotypes that  had no annotations **even** if they were part of multi gene genotypes. I have only done this when I was fixing allele names/descriptions  to reduce the amount of editing I needed to do. This might be the route of the problem and does fit with the sessions. Probably  the single gene allele needs to exist and is recreated once the multi allele is edited.  but something in the code is making the recreation of the allele happen multiple times

**Comment by kimrutherford** [comment] 2023-03-13 01:54
> Probably the single gene allele needs to exist and is recreated once the multi allele is edited. but something in the code is making the recreation of the allele happen multiple times

Yep, I think you're right but I still can't reproduce the problem.  :-(

I've done some testing, deleting single allele genotypes.  They do get recreated but I haven't been able to trigger it to create duplicates.

**Comment by ValWood** [comment] 2023-03-13 07:56
If you delete an  allele that isn't used in a single genotype, but it is used in multple multi-gene genotypes, it will recreate the single allele for each one.

tested here:
curs/d4e73d1a93ec5860/genotype_manage

there are 2 
hts1-S121A

**Comment by kimrutherford** [comment] 2023-04-16 08:05
> They do get recreated but I haven't been able to trigger it to create duplicates.

I can now reproduce this.  It's a problem with the asynchronous way that Javascript works.  I haven't thought of a fix yet.

**Comment by kimrutherford** [comment] 2023-12-04 07:16
I've attempted a fix for this.  I've deployed only in the test Canto for now as it needs some testing.

**Comment by kimrutherford** [comment] 2023-12-05 01:58
> I've deployed only in the test Canto for now as it needs some testing.

It all seems OK in the test Canto, but this is a hard bug to reproduce on demand.  I think it's fixed so I've deployed the change on the main Canto instance.

If you still see this happening, please re-open.

**Closed by kimrutherford** 2023-12-05 01:58 UTC
Labels: bug, high priority
