### ISSUE TITLE
Allow extensions on interactions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1043] opened 2015-12-04 11:49 UTC
We should make the extension interface available for interactions.  We need to discuss how we would configure that.

@airvine

**Comment by Antonialock** [comment] 2015-12-08 13:28
Well, there's no way of displaying them at the moment. I'm not too fussed to be honest..

**Comment by ValWood** [comment] 2015-12-09 16:54
I think its something we should think about.  We could link phenotypes to  genetic interactions.
It isn't something we need urgently but if Alistair does it should be high on the list.

**Comment by kimrutherford** [comment] 2015-12-09 21:10
Midori suggested that you might want to record the cellular component of an interaction (if I'm remembering correctly).

**Comment by mah11** [comment] 2015-12-10 09:45
yup, or cell cycle phase when an interaction happens

**Comment by kimrutherford** [comment] 2015-12-17 04:15
I think I know how the display and display code will work for adding
extensions to interactions, but we need to think about how it would be
configured.

**Comment by kimrutherford** [comment] 2015-12-17 11:44
> but we need to think about how it would be configured

I'll have a chat to Alistair about the PHI-Base requirements before going further.

**Comment by airvine** [comment] 2015-12-21 19:09
In PHI-base, I have a number of problems with trying to use genetic or physical interactions. Most of these revolve around the fact that PHI-base is trying to annotate "Pathogen-Host Interactions", rather than just annotating genes - so if we take the genes selected in the Canto tool as being pathogen genes, then we still need to know which "PHI interaction" it is associated with. In principle I could identify the host organism from the taxon associated with the UniProt entry, but the definition of the "PHI interaction" also includes pathogen & host strain info and conditions such as anti-infective chemistry. For phenotypes, all of the specifying data is in the annotation extensions. Without any extensions, it is impossible to link the interaction to a corresponding "pathogen-host interaction" - since an individual gene can have multiple "PHI interactions", and each PHI interaction can have multiple annotations.

Another difficulty in grouping data together to meaningful "PHI interactions" is that while the phenotypes are annotated against precise genotypes - with specific allele information - the interactions are just annotated against a single gene, so it becomes difficult to make the connection between them. It may be easier for me to change my database schema such that the genetic and physical interactions  are only associated with the gene, and not (directly) with the "PHI interaction".

One of annotations I was trying to capture with interactions was the "host first target protein", i.e. the host protein that the pathogen gene of interest interacts with. The problem is that to capture this info I have to first add the pathogen gene to Canto. When I do this, the list of genes is no longer a list of pathogen genes, but rather a mixture of genes that represent both pathogen and host genes. The problem is that there is no obvious way of knowing which ones are pathogen genes and which ones are host genes. If I were to try to fully annotate both types of genes then I would want the annotation extensions to be different.

This was not such a problem before developing the annotation extension interface, because then I was simply annotating the "host first target protein" using the UniProt identifier as a string in the annotation extension - so the protein would not be added to the list of genes. Perhaps I should revert back to capturing the info in this way.

In PHI-base I'm trying to capture info like this:
pathogen gene -> host -> pathogen-host interaction annotation

But Canto works like this:
gene -> gene annotation -> annotation extension

I try to configure Canto for PHI-base so that it can be interpreted like this:
pathogen gene -> pathogen gene annotation -> extension specifying host

But this causes a problem if I try to use genetic or physical interactions to specify the interacting protein in a host, because I have to add the host gene to the full list of genes, so now my list of genes becomes a mixture of pathogen genes and host genes.

**Comment by ValWood** [comment] 2016-01-02 14:07
Hi Alistair,

The curation types "genetic interaction" and "physical interaction" are configured to capture "bioGRID format" genetic and physical interactions,  and the scope is within species genetic and physical interactions. For  genetic interactions  (2 of 2+ genes) associated with specific phenotypes we use the "multi gene phenotype"  option as we can capture conditions this way (the BioGrid format  does not allow us to capture the specific detail we require to associated with such multi gene phenotypes, but we use it because we have a long term collaboration to exchange data). 

I think the way forward here will be to adapt this to your needs. I think we are still struggling a little in understanding the PHIbase concept of an 'interaction' and what data you collect together into a single 'interaction'.

For example, above what biological information are you trying to represent? If I understood correctly you are representing a physical interaction between one  pathogen protein and one host protein.   Is this always the case?
If so we could  maybe provide a configuration option to allow the capture of a physical interaction between a pathogen and a host protein.

What other  information are you trying to link this to? I wonder if these connections could be made "behind the scenes" if all of the relevant information is captured. I think  first  we need some more concrete biological examples to understand more fully what you require.

Val

**Comment by airvine** [comment] 2016-01-06 19:34
I did think it would be better to save the interactions via phenotypes, then use the appropriate evidence to specify that the phenotype arose from an interaction of the (pathogen) gene with another gene, which would be from the host. This makes it much easier to connect the different annotations into a single "PHI interaction", but still has the problem of having the host gene added to the overall list of genes. It would be better if I could add the host gene (via a UniProt accession) to specify it's physical interaction with the pathogen gene, but just without this host gene being added to the overall list of genes. At the moment, the only way I can do this is to keep specifying the physical interaction as an annotation extension, which allows me to specify the host gene via text - this way it is not added to the overall list of genes (but then the UniProt lookup is lost). I can cope with it like this for the the time being.

I'll try and find a few examples.

**Comment by airvine** [comment] 2016-01-08 12:57
A relatively simple example would be from [PubMed ID 15096512](http://www.ncbi.nlm.nih.gov/pubmed/15096512), where pathogen protein EPI1 physically interacts with host protein P69B.

A more complex example would be from [PubMed ID 20601497](http://www.ncbi.nlm.nih.gov/pubmed/20601497), where pathogen protein ATR1 physically interacts with host protein RPP1. In this case different phenotypes are observed depending on both the pathogen isolate and the host ecotype selected. This is an example where a single paper for a single pathogen gene may have several different "pathogen-host interactions" (based on the specific pathogen isolate and host ecotype). Each "PHI interaction" would potentially have many different annotations associated with them, but I still need to be able to somehow group the pathogen gene annotations into their respective "PHI Interaction" - i.e. a need to know which gene annotations are associated with which pathogen isolates and host ecotypes.

**Comment by ValWood** [comment] 2016-01-20 08:10
Hi Alistair. We plan to look at these papers and curate how we would  curate them. Then we can work with you to figure out what else is needed. From a brief discussion on our  weekly call we think you will need a new curation type, but we still need to understand better what you need. We hope to get to it next week.....but its high on the list.

Val

**Comment by airvine** [comment] 2016-01-22 16:54
For the two example papers above, I have attempted to curate the details into [PHI-base Canto](http://curation.phi-base.org/ ).

I think it might be useful for you to see the annotations as I have been entered them into PHI-base Canto, so that you can see our configured interface and how we are handling the data. For testing purposes, I have given you all admin access using your email and `cantotest` as the password.

These publications are papers that my colleague Alayne Cuzick (@CuzickA), our PHI-base curator based here in Rothamsted, has recently being attempting to curate. She understands the underlying biology better than I do, so may be able to add her own comments.

Alayne has also curated the same papers into our current PHI-base spreadsheet, which may be useful for you to look at (this includes another paper [PMID:15980196](http://www.ncbi.nlm.nih.gov/pubmed/15980196), which is similar to PMID:15096512):
[phi4_2016-01-15_alayne_curation_examples.xlsx](https://github.com/pombase/canto/files/101077/phi4_2016-01-15_alayne_curation_examples.xlsx)

For PMID:20601497, there are a lot of phenotypes that vary depending on the partial deletions in the host target gene (not the pathogen gene). I currently don't have an annotation extension to cope with modifications to the host gene, so for the moment I have this in as a comment to the annotation

**Comment by ValWood** [comment] 2017-10-29 16:06
closing, will open new tickets  but the PHI-base interaction is a type of phenotype not a canto type of interaction so this ticket is confusing

**Closed by ValWood** 2017-10-29 16:06 UTC
Labels: extension interface, feature request, PHI-base
