### ISSUE TITLE
PHI-Canto PHI phenotype 'extensions problem'

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1262] opened 2016-09-27 10:36 UTC
The PHI-Canto prototype tool has a minor bug regarding adding annotation extensions to the first PHI phenotype annotation. The annotation term ‘unaffected pathogenicity’ must be selected to enable the option of adding annotation extensions. Once the annotation has been completed the author can then go back into the annotation using the edit button and modify the PHI phenotype annotation to that required for example ‘reduced virulence’.

**Comment by ValWood** [comment] 2016-09-27 14:27
This might be a configuration issue. The allowed extensions for particular terms are configurable in an external file. This allows flexibility for curators to specify which terms can be extended.
Do you have any extensions options appearing at all?
We can work from there.

**Comment by kimrutherford** [comment] 2016-09-28 03:10
Hi Alayne.  Is there a test version of PHI-Canto that I can try to reproduce this in?  We haven't seen this bug in the pombe Canto.

**Comment by fusarium** [comment] 2016-09-28 07:13
We set up a test version of PHI-canto at http://curation-test.phi-base.org/ that could be used for testing.

**Comment by kimrutherford** [comment] 2016-09-28 08:22
Thanks for the link.  Could you send or attach the annotation extension configuration file for the PHI phenotypes?  The file name should be list under the "extension_conf_files" configuration item in canto_deploy.yaml.  Thanks.

**Comment by ValWood** [comment] 2016-09-28 08:25
i don't really know whether I am testing the correct thing, but I just tried to annotate "unaffected pathogenicity" in your test tool, and I see the following annotation extension options for this term:

![test](https://cloud.githubusercontent.com/assets/7359272/18905963/7372ec3a-855d-11e6-97e5-890582773cb1.jpg)

**Comment by kimrutherford** [comment] 2016-09-28 08:27
The problem is that the extension don't appear for "reduced virulence".

**Comment by ValWood** [comment] 2016-09-28 08:39
Oh yes...that does sound like a config issue.

**Comment by CuzickA** [comment] 2016-09-28 08:40
Hi Kim, Martin said he would look for the requested file and send shortly. 
Yes, the problem is that extensions only appear for unaffected pathogenicity and nothing for the other phenotypes eg reduced virulence.

**Comment by kimrutherford** [comment] 2016-09-28 08:46
Thanks.  I should have asked about the OBO file for the PHI phenotype ontology.  Could you send that too?

**Comment by CuzickA** [comment] 2016-09-28 08:49
We will look into finding that file and sending it to you soon.

**Comment by fusarium** [comment] 2016-09-28 14:51
Will send the files by email now. They don't appear to upload into Github as ZIP from Windows.

**Comment by kimrutherford** [comment] 2016-09-29 11:49
Thanks for sending the files.  The OBO file and configuration look OK to me.  I suspect the reason I can't reproduce the problem is that it has been fixed between the version you're using and the current version.  So an upgrade of your Canto might fix things.

I haven't yet tried to load your OBO and config files into a test Canto with the latest code.  I've run out of time today, but I'll try that tomorrow.

**Comment by kimrutherford** [comment] 2016-09-30 10:50
> I haven't yet tried to load your OBO and config files into a test Canto with the latest code.

I've tried that now and it all looks fine in the latest code.  The annotation extension handing code in the version you are using was still quite experimental.  Many bug fixes have been made since then.

So I think the next thing to try is to upgrade to the latest code.  Unfortunately that might be difficult.  I've had a look at the version here: https://github.com/PHI-base/canto
and there are many PHI-Base specific changes so merging the latest PomBase code will cause many conflicts.  I'm happy to help if you'd like to try that.  I could also try doing the merge myself if that would help.

**Comment by kimrutherford** [comment] 2016-10-02 22:50
> So I think the next thing to try is to upgrade to the latest code.

I've now done that:
  https://github.com/kimrutherford/canto/tree/phibase-canto-master

I haven't done any testing with it yet.  The merge was complicated because the PHI-Base version had many changes.

**Comment by fusarium** [comment] 2016-10-03 09:33
Hi Kim,
could you try the update on our test server for 'http://curation-test.phi-base.org/' as I am not familiar with the environment yet?
I would be interest some time later in a 'tour' when you have the time .

**Comment by kimrutherford** [comment] 2016-10-03 09:58
Hi Martin.  I'm happy to try that.  Could you create an account for me on that machine and let me know how to login?

**Comment by fusarium** [comment] 2016-10-03 13:35
Will do by email.

**Comment by kimrutherford** [comment] 2016-10-05 02:37
> I've now done that:
>  https://github.com/kimrutherford/canto/tree/phibase-canto-master

I've had another look at this.  Canto has a file of configuration defaults (canto.yaml) and a file for installation specific changes (canto_deploy.yaml).  There were many PHI-Base specific changes in canto.yaml that I have now pulled into canto_deploy_phibase.yaml.

canto_deploy_phibase.yaml should be copied to canto_deploy.yaml on the server after updating the code.

**Comment by ValWood** [comment] 2017-11-03 15:34
closing as out of date.

**Closed by ValWood** 2017-11-03 15:34 UTC
Labels: bug, high priority, PHI-base
