### ISSUE TITLE
gene expression curation

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1491] opened 2018-06-11 14:14 UTC
Transferred from #20 (which is a bit of a catchall as well as kind of old) ...

Val:

I think first we would like to be able to do "expression levels" in Canto as that is the one we use the most. Also, if this was added it would deter people from curating WT expression phenotypes (which is now possible).

Should we use expression as a test?
I think we might only need to make a mini ontology and config files and then tell kim what
label we want ?
https://curation.pombase.org/pombase-trac/wiki/CapturingGeneExpression

@mah11 could you have a stab at this part when you get chance?
I'm guessing it will be very quick for Kim to implement once we have this?

**Comment by mah11** [comment] 2018-06-11 14:15
Kim: 



>   I think we might only need to make a mini ontology and config files and then tell kim what
>   label we want ?

Yep, as long as you don't need to need to specify expression levels as percentages too.

Are you planning on just having terms like high, medium, low etc.?

**Comment by mah11** [comment] 2018-06-11 14:15
Val:

th[is] would only be for qualitative.

quantitative are rarer and usually HTP and we will do these in the spreadsheet

so we probably don't need to capture numbers in canto

https://www.pombase.org/documentation/quantitative-gene-expression-data-bulk-upload-format

@mah11 @Antonialock ?

**Comment by mah11** [comment] 2018-06-11 14:15
Kim:

> this would only be for qualitative.

Great. In that case it probably only configuration is needed.

**Comment by mah11** [comment] 2018-06-11 14:16
Val:

Wonderful!

**Comment by mah11** [comment] 2018-06-11 14:24
Kim:

I've just tried it.  The basics work but there is a but of tweaking to do.

We don't want to show "FYPO expressivity extension" in the dropdown.  And instead of "Start typing a Wild type expression level" we want to say something like "Select a Wild type expression level ...".  In fact the whole paragraph needs fixing.

![wild-type-expression-select-1](https://user-images.githubusercontent.com/90474/41222657-a6a6df92-6dbb-11e8-9ce9-4f57c225b958.png)

We can make an annotation though:

![wild-type-expression-annotation-1](https://user-images.githubusercontent.com/90474/41223224-58b3e79c-6dbd-11e8-94d3-5a58b7a5ad02.png)

**Comment by mah11** [comment] 2018-06-11 14:24
Val:

Great.
If Midori can suggest text/teaks we can get this into live...

**Comment by mah11** [comment] 2018-06-11 14:48
and finally, my comments:

> We don't want to show "FYPO expressivity extension" in the dropdown.

Indeed we don't. Gene expression has nothing whatsoever to do with phenotype expressivity extensions, and vice versa. (I suppose that adds to the case for changing "expressivity" to "severity", but that's a tangent.)

To create a gene expression annotation, annotators should follow these steps:

- Choose a gene.
- Choose one of 'RNA level' or 'protein level'. Accompanying text: "Select what was measured (RNA or protein)"
- Choose a qualifier. This can come from a mini-ontology, so if that's a good way to do it, I'll make one. Do.not.use. FYPO_EXT for this. Accompanying text: "Select a description" (can make this longer if you think it needs more, but the set probably is small enough for just a pulldown)
- Choose evidence. Suggested list below.
- Add one or more extensions. I can make a config file for this. Use the usual "these extension types are available" text.

For evidence, I suggest a pulldown with text that we map to ECO. It'd be best if we restrict the options to what's relevant to the selected RNA or protein. It should include:

|RNA or protein|text for pulldown|ECO id|ECO name|
|----|----|------|--------|
|RNA|Northern blot|ECO:0005653|northern assay evidence used in manual assertion
|RNA|quantitative PCR|ECO:0005660|quantitative polymerase chain reaction evidence used in manual assertion|
|RNA|reporter gene assay|ECO:0000049|reporter gene assay evidence|
|RNA|microarray|ECO:0000275|expression microarray evidence used in manual assertion|
|RNA|other transcript expression level assay|ECO:0000291|transcript expression evidence used in manual assertion|
|protein|Western blot|ECO:0000279|western blot evidence used in manual assertion|
|protein|reporter gene assay|ECO:0000049|reporter gene assay evidence|

Have I missed any? I looked at evidence we've used in artemis, omitting ones used for other annotation types, and updated the selection a bit.


An annotation might look like:

|Gene|level|Term ID|Term name|Evidence|Annotation extension|
|--|--|--|--|--|--|
|mrc1|RNA level|PomGeneEx:0000001|increased|ECO:0005653|during mitotic S phase|

We can display the full ECO term name or the shorter text from the pulldown in addition to or instead of the ECO ID. For the qualifiers I picked the ontology name out of thin air, so we can change it before this all goes anywhere near live, and we could display just the term name, or put the ID in paretheses instead of a separate column. I don't really mind ...

Comments, whinges, suggestions?

**Comment by ValWood** [comment] 2018-06-11 14:53
Sounds good to me.

**Comment by kimrutherford** [comment] 2018-06-12 02:45
> Choose a qualifier. This can come from a mini-ontology, so if that's a good way to do it, I'll make one.

OK, we'll need the new ontology then. 

> Do.not.use. FYPO_EXT for this.

It was handy for testing.

**Comment by mah11** [comment] 2018-06-12 16:49
> OK, we'll need the new ontology then.

I made and committed mini-ontologies/pombase_gene_expression_ontology.obo

I also did a very small extension config file - the file name isn't _quite_ longer than the contents but it's close: supporting_files/annotation_ex_config/PomGeneEx_A_E_config.

> [FYPO_EXT] was handy for testing.

Fair enough :)

**Comment by Antonialock** [comment] 2018-06-13 16:12
also here is the wiki page 
https://curation.pombase.org/pombase-trac/wiki/CapturingGeneExpression

**Comment by ValWood** [comment] 2018-06-21 06:57
Anything to discuss here?

**Comment by ValWood** [comment] 2018-06-28 09:57
What needs to happen here next?

We can chat about this if necessary

**Comment by ValWood** [comment] 2018-06-28 12:11
once this is working, this one should be easy
https://github.com/pombase/canto/issues/20

**Comment by ValWood** [comment] 2018-07-18 13:46
@kimrutherford  waiting for you to see if the files Midori created are OK.

We can chat about this tomorrow?

**Comment by ValWood** [comment] 2019-09-03 21:46
It seems like this was nearly implemented. MAybe we should get this up and running ?
can discuss on next call what still needed.

**Comment by ValWood** [comment] 2020-04-28 10:58
Also requiredd by PHI Base.

https://github.com/PHI-base/curation/issues/74

 We can discuss soon, since it  might be largely configuration.
I'll review this ticket  and summarize.

**Comment by ValWood** [comment] 2020-04-28 10:59
It would be nice to bring these into  Canto, it;'s a pinta doing them in Artemis, Also would be good to make available to the community

**Comment by ValWood** [comment] 2020-06-11 15:26
Hi Kim,

Let me know if you want to chat about this one.
Now that query naming is working, this looks like something that is nearly complete and would be useful to do before a bigger task.

I'm not sure if. you are missing any information, But I think we discussed and you said not...

**Comment by kimrutherford** [comment] 2020-06-25 05:13
Can we get away with implementing this using two new annotation types inside of one?:

![screen](https://user-images.githubusercontent.com/90474/85657648-69be7e00-b706-11ea-81ff-62bcaaae992f.png)

![choose](https://user-images.githubusercontent.com/90474/85657806-98d4ef80-b706-11ea-9d96-47db16d361f8.png)

![screen01](https://user-images.githubusercontent.com/90474/85657833-a38f8480-b706-11ea-8b74-f55f2047392e.png)

We can hide things like extension and the term suggestion boxes:

![edit](https://user-images.githubusercontent.com/90474/85658270-29abcb00-b707-11ea-9732-8f395ae7144a.png)

**Comment by ValWood** [comment] 2020-06-25 06:22
|If it is easier I don't see why not...

**Comment by mah11** [comment] 2020-06-25 08:38
no objection

**Comment by kimrutherford** [comment] 2020-06-25 08:58
I've added what I have done so far to the test tool: https://curation.pombase.org/test/

I've also just added "subset: qc_do_not_annotate" to:
```
[Term]
id: PomGeneEx:0000001
name: gene expression qualifier
```
so it isn't offered as an option in the interface.  That change isn't visible yet.

Things to do:
  - use the EBO evidence codes
  - remove this section from the long workflow (unless you think it should stay):
> The currently selected term has no children. If you need a more specific term to describe the experiment you are annotating, please follow the link below to suggest it:

What other changes are needed?

**Comment by mah11** [comment] 2020-06-25 13:39
>    remove this section from the long workflow (unless you think it should stay):
> 
> >    The currently selected term has no children. If you need a more specific term to describe the experiment you are annotating, please follow the link below to suggest it:

I think it could go.

> What other changes are needed?

It needs the extensions - the annotations aren't very meaningful without them. Will it help if I do a draft extension config file?

**Comment by mah11** [comment] 2020-06-25 13:42
I suppose for these we could also hide the "Term ID" column in the annotation tables - the PomGeneEx IDs won't mean much to anyone, and it won't hurt to save the space for the extensions (some will mention GO terms).

**Comment by ValWood** [comment] 2020-06-25 18:39
I'll test once the extensions are in place.

**Comment by kimrutherford** [comment] 2020-06-26 00:06
> use the EBO evidence codes

Or even ECO evidence codes.  :-)

That's done now.

> It needs the extensions - the annotations aren't very meaningful without them. Will it help if I do a draft
> extension config file?

Thanks, that would be great.

**Comment by kimrutherford** [comment] 2020-06-26 01:51
> remove this section from the long workflow (unless you think it should stay):
> The currently selected term has no children. If you need a more specific term to describe the experiment you are annotating, please follow the link below to ...

I've removed that for gene expression annotations.

**Comment by mah11** [comment] 2020-06-26 12:58
> > ...   extension config file?
> 
> Thanks, that would be great.

Well, we're unobservant numpties. I did the config file ages ago, as noted [above](https://github.com/pombase/canto/issues/1491#issuecomment-396658708). It has since moved to GitHub at pombase-config/canto/annotation_ex_config/PomGeneEx_A_E_config.

**Comment by kimrutherford** [comment] 2020-06-27 08:01
Thanks.  The gene expression extensions are now configured and loaded in the test Canto.

**Comment by mah11** [comment] 2020-06-30 09:32
That seems to be working well. I've had a thought: specifically for gene expression, it might make sense to switch a couple of the steps in the "newbie" step-by-step interface so that extensions come before evidence. It'll flow more naturally for people to think "the level is *increased* during *mitotic S phase* and we did a *western blot* to see it" than to have the evidence pop in between "what happens" and "when".

**Comment by ValWood** [comment] 2020-07-01 13:18
I don't see the expression options in test Canto (I was going to test)

**Comment by mah11** [comment] 2020-07-01 13:56
Hmm, they're there for me - "RNA level" and "protein level" on the gene-specific pages all the time, and on the summary page when advanced mode is active. Maybe shift-refresh if you don't see them?

**Comment by kimrutherford** [comment] 2020-07-01 22:57
Yep, the gene-ex annotation types are definitely there:
![test-gene-ex-1](https://user-images.githubusercontent.com/90474/86298780-ba782e80-bc52-11ea-85fb-dfe641de6281.png)

**Comment by ValWood** [comment] 2020-07-02 09:46
Yes I don't know whey I didn't see it. I had a play last night. Is working fine. I had a couple of comments  that I'll submit in a min when I got through e-mail.

**Comment by ValWood** [comment] 2020-07-02 13:13
All seems to be working.

Comments:

1.
> > remove this section from the long workflow (unless you think it should stay):
> > The currently selected term has no children. If you need a more specific term to describe the experiment you are annotating, please follow the link below to ...
> 
> I've removed that for gene expression annotations.

The ability to suggest a descendant is still visible, but isn't required because this is a 'flat list'

2. Is this currently using the extension restrictions @mah created above (it seems to allow a lot  of  terms currently)

**Comment by ValWood** [comment] 2020-07-02 13:15
> Val:
> 
> th[is] would only be for qualitative.
> 
> quantitative are rarer and usually HTP and we will do these in the spreadsheet
> 
> so we probably don't need to capture numbers in canto
> 
> https://www.pombase.org/documentation/quantitative-gene-expression-data-bulk-upload-format
> 
> @mah11 @Antonialock ?

Above I said only for qualitative. Increasingly it will likely be quantitative and I have created tables for some.
We could have  options  for

Copies per cell,  range
and if these were  completed, and annotation  would automatically be classes as "quantitative"

Also if these options after selected, we might want  to be able to specify "singe-cell" too.

**Comment by mah11** [comment] 2020-07-02 13:23
> Is this currently using the extension restrictions @mah created above (it seems to allow a lot of terms currently)

What's offered for "during" seems consistent with the configuration.

"In presence of" currently allows any CHEBI substance. We may be able to think of ways to narrow that, but I wouldn't delay deploying this for it, since it's easy to adjust the extension config any time (the hard part will be figuring out what to include/exclude - at the moment I have no idea).

**Comment by ValWood** [comment] 2020-07-02 13:50
Yes  the extension restirctions are fine.

I was confused by seeing
GO:0098779    positive regulation of mitophagy in response to mitochondrial depolarization
but that is under "response to" terms in GO

**Comment by kimrutherford** [comment] 2020-07-03 02:10
> The ability to suggest a descendant is still visible, but isn't required because this is a 'flat list'

That's fixed in the test Canto now.

**Comment by kimrutherford** [comment] 2020-07-28 02:46
What else needs to be done for this issue?

**Comment by ValWood** [comment] 2020-07-28 07:47
Ah sorry,I dropped the ball... we should do a quick  final test and move to live?

**Comment by kimrutherford** [comment] 2020-07-28 08:00
Do we need extra documentation since it's a new annotation type?

**Comment by mah11** [comment] 2020-07-28 09:12
> Do we need extra documentation since it's a new annotation type?

Yes, but I think I could put some together pretty quickly. Give me a day or two notice ...

**Comment by ValWood** [comment] 2020-07-28 12:10
- [ ]. quick add seems to work, but clicking directly on the annotation type does not

- [ ]  I don't think we want to allow term suggestions here. It's a very restricted set and  we have never really needed a new term. It's so rare that we would probably rather the user mailed us (also there is the comment filed)

**Comment by ValWood** [comment] 2020-07-28 12:12
Otherwise, all seems to be working nicely.

**Comment by mah11** [comment] 2020-07-28 12:21
> quick add seems to work, but clicking directly on the annotation type does not

it works for me

>  I don't think we want to allow term suggestions here.

I agree; note that suggestions have already been removed from the step-by-step procedure, so it's only the quick-add version that still needs changing.

**Comment by mah11** [comment] 2020-07-28 12:25
Any thoughts on the evidence/extension order suggestion from above?

https://github.com/pombase/canto/issues/1491#issuecomment-651679564

Not worth delaying release, but I didn't want the idea to get lost.

**Comment by ValWood** [comment] 2020-07-28 12:38
Wierd. It's working now...

**Comment by ValWood** [comment] 2020-07-28 12:39
> Any thoughts on the evidence/extension order suggestion from above?

I agree.

**Comment by kimrutherford** [comment] 2020-07-28 19:29
> quick add seems to work, but clicking directly on the annotation type does not

What was the symptom?

**Comment by ValWood** [comment] 2020-07-29 08:31
It was only showing the gene name. I saw no term selection box. I tried a couple of times but maybe it was a network glitch because the issue went away.

**Comment by ValWood** [comment] 2020-08-05 07:53
can. this go live? 
documentation can follow...

**Comment by kimrutherford** [comment] 2020-08-05 08:08
I haven't yet fixed the problems you found.

**Comment by mah11** [comment] 2020-08-05 08:13
I really don't like taking a "documentation can follow" attitude ... but I can work on documentation this afternoon.

**Comment by ValWood** [comment] 2020-08-05 08:53
>I really don't like taking a "documentation can follow" attitude ... but I can work on documentation this afternoon.

I wouldn't normally but its quite self explanatory and it would not harm for a day or two.... it's such faff to go into Artemis and then I always need to look up the terms on the wiki etc....
...although the paper that I was just curating and I thought had expression level data did not, so my urgency just went away!

**Comment by ValWood** [comment] 2020-08-05 08:53
>I haven't yet fixed the problems you found. 

weren't they non-issues. I could not reproduce...

**Comment by ValWood** [comment] 2020-08-05 09:14
I tried again and I'm sure the problems I was experiencing were due to the slowness of the test server. It works fine if I am patient.

Still to do for release:

- [ ] remove term suggestion box from quicklinks
- [ ] documentation
- [ ] change the ordering so that extensions come before evidence (full and quicklinks interface)

>Later:

- [ ] Above I said only for qualitative. Increasingly it will likely be quantitative and I have created tables for some.
We could have options for
Copies per cell, range
and if these were completed, and annotation would automatically be classed as "quantitative"
Also, if 'copies per cell' was selected, we might want to be able to specify "singe-cell" too.

We do not need to wait for this because we can do them in a mini spreadsheet. But it would be nice. Maybe move this item to a new ticket  with low priority, and raise the priority if we  begin to get a lot of small-scale quantitative (I  have done some recently)

**Comment by kimrutherford** [comment] 2020-08-05 09:38
> change the ordering so that extensions come before evidence (full and quicklinks interface)

Is that just for expression curation or is it for all annotation types?

**Comment by mah11** [comment] 2020-08-05 09:44
>>  change the ordering so that extensions come before evidence (full and quicklinks interface)
> 
> Is that just for expression curation or is it for all annotation types?

In the step-by-step version, it's just for expression. (The quick interface already has extensions before evidence for everything else, which is fine.)

**Comment by kimrutherford** [comment] 2020-08-05 10:45
> In the step-by-step version, it's just for expression.

OK, thanks.  Unfortunately, that's not a quick fix as the workflow code is not simple.

**Comment by mah11** [comment] 2020-08-05 12:06
>> In the step-by-step version, it's just for expression.
> 
> OK, thanks. Unfortunately, that's not a quick fix as the workflow code is not simple.

Drat. But if it isn't easy to do, we can knock it back to "would be nice in the foreseeable future".

**Comment by ValWood** [comment] 2020-08-05 13:59
Do we have any objection to always having the extensions before the evidence?

**Comment by mah11** [comment] 2020-08-05 16:35
OK, I have committed some documentation. I hope I haven't screwed up any formatting ...

**Comment by kimrutherford** [comment] 2020-08-05 22:42
> Do we have any objection to always having the extensions before the evidence?

It sort of makes sense to me to collect the required data first, followed by the optional fields (like extensions).

**Comment by kimrutherford** [comment] 2020-08-11 04:46
> remove term suggestion box from quicklinks

That's done now.

**Comment by kimrutherford** [comment] 2020-08-24 02:51
> It sort of makes sense to me to collect the required data first, followed by the optional fields (like extensions).

Although it also makes sense to have the extension page straight after the term page since the available extensions depend on the term.

Also still to do:

> I suppose for these we could also hide the "Term ID" column in the annotation tables - the PomGeneEx IDs won't mean much to anyone, and it won't hurt to save the space for the extensions (some will mention GO terms).

**Comment by kimrutherford** [comment] 2020-08-31 03:45
> Also still to do:
> 
> > I suppose for these we could also hide the "Term ID" column in the annotation tables - the PomGeneEx IDs won't mean much to anyone, and it won't hurt to save the space for the extensions (some will mention GO terms).

That's done now.

**Comment by ValWood** [comment] 2020-10-15 15:07
It seems that this is done but I am not sure of the status. I'm asking because I have an example where a user has curated expression level in phenotypes using WT alleles. I have seen this a few times now. It would be great to get this into Canto to prevent this (and also speed up for us as currently we need to enter these in Artemis).

So what is outstanding here? It seems that the code and the docs are done. Does it just need moving to live?

**Comment by kimrutherford** [comment] 2020-10-16 01:05
> It seems that this is done but I am not sure of the status. 

I think it just needs testing and a final decision on this:

> Do we have any objection to always having the extensions before the evidence?

**Comment by ValWood** [comment] 2020-10-16 08:48
> Do we have any objection to always having the extensions before the evidence?

I don't mind

I think we are happy h from the previous testing . I just tested again in case any thing changed and it all seems to be good.

**Comment by kimrutherford** [comment] 2020-10-16 09:09
OK.  Thanks for testing.  I'll deploy it on my Monday (your Sunday night) so it will be ready on UK Monday morning.

**Comment by kimrutherford** [comment] 2020-10-19 00:44
> I'll deploy it on my Monday (your Sunday night) so it will be ready on UK Monday morning.

I've enable the gene expression types.  The extensions aren't available for them yet because they get updated when the nightly ontology update runs.  I've just (1:45am) kicked that off so it should be ready well before morning.

@jseager7 if you need to disable these new annotation types for PHI-Canto, let me know.

**Comment by jseager7** [comment] 2020-10-19 09:35
> @jseager7 if you need to disable these new annotation types for PHI-Canto, let me know.

Based on https://github.com/PHI-base/curation/issues/74, it looks like PHI-Canto needs these annotation types too.

**Comment by kimrutherford** [comment] 2020-10-19 11:10
> it looks like PHI-Canto needs these annotation types too.

OK, thanks for checking.

You'll need to load this OBO file containing the terms for gene expression annotation:
https://curation.pombase.org/dumps/latest_build/pombe-embl/mini-ontologies/pombase_gene_expression_ontology.obo

And you'll need add this file to the `extension_conf_files` extension config:
https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/PomGeneEx_A_E_config
and then run the ontology update.

Let me know if you have any problems.

**Comment by jseager7** [comment] 2020-10-19 11:38
Thanks. I've made the necessary changes to our config repository, now I just need to test them on our test or demo server.

**Comment by jseager7** [comment] 2020-10-19 14:16
@kimrutherford The configuration and ontologies seemed to load with no errors, but how do I actually test this functionality in Canto? I don't see any new annotation types on the gene page. Is there any other configuration needed in `canto_deploy.yaml`, besides the `extension_conf_files` property?

**Comment by kimrutherford** [comment] 2020-10-19 22:08
Is this your current config?:
https://github.com/PHI-base/config/blob/master/canto_deploy.yaml

If so you'll need to add the definitions for ```wt_rna_expression``` and ```wt_protein_expression``` to:
```available_annotation_type_list```
(by copying from canto.yaml)

And you'll need to add wt_rna_expression and wt_protein_expression to:
```enabled_annotation_type_list```

**Comment by jseager7** [comment] 2020-10-20 08:29
Thanks. That enabled the RNA level and Protein level annotation types. I've created two test annotations and didn't see any problems.

**Comment by kimrutherford** [comment] 2020-10-20 09:40
>  I've created two test annotations and didn't see any problems.

Great.  Thanks for the update.

Val, I think we can close this if you're happy.

**Comment by ValWood** [comment] 2020-10-20 15:33
Great. I will move this:

Later:

 Above I said only for qualitative. Increasingly it will likely be quantitative and I have created tables for some.
We could have options for
Copies per cell, range
and if these were completed, and annotation would automatically be classed as "quantitative"
Also, if 'copies per cell' was selected, we might want to be able to specify "singe-cell" too.
We do not need to wait for this because we can do them in a mini spreadsheet. But it would be nice. Maybe move this item to a new ticket with low priority, and raise the priority if we begin to get a lot of small-scale quantitative (I have done some recently)

to a new ticket

**Closed by ValWood** 2020-10-20 15:33 UTC
Labels: PHI-Canto, config, discuss, high priority, new data types, next, required for Artemis migration
