### ISSUE TITLE
Current curator changed into Admin Person

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2431] opened 2021-03-10 16:41 UTC
Hi Kim,

When I tried to generate phen records from Canto json I've encountered the same error for 9 papers:

spica:~ ao493$ makephen
Name of canto json export file (fullpath):/export-vm/staging/canto_export_json/canto-flybase-export-21-03-10.json
Please enter the curation record prefix, e.g. gm :ao
Please enter the number that the first curation record should start at, e.g. 14386 :211
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
0ba487987686dca9	PMID:25564670	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
51e83fb281b10195	PMID:25503410	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
54435209aa5d4736	PMID:25660543	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
5a9b86ccb619145a	PMID:25731175	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
877f2d9e40880eca	PMID:25843034	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
8f865baab6b9cda0	PMID:21558376	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
a9dc831f8657fdcc	PMID:25451193	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
d002d67022efea28	PMID:25714570	Admin Person
Use of uninitialized value in string eq at /export-vm/support_scripts/canto_json_output_parser.pl line 687.
The following approved session belongs to another curator, will not turn this into proformae:
fa93d50bf55e25c6	PMID:25781970	Admin Person

While for two papers, PMID:26042831 and PMID:25958090, there weren't any issues. Would it be possible that I might have started curating (after assigning myself as the curator) after the update and that is why they were okay?

Could you please look into this issue and let us know what you think has happened?

Many thanks.
Arzu

**Comment by gm119** [comment] 2021-03-11 10:00
Hi @kimrutherford  - oh, I said I thought this was one for you ;)

I think the issue is that the curator is recorded in Canto as 'Admin Person', rather than an individual name.
My code does have a mapping of individual names to prefixes (so e.g. it 'knows' that ao is Arzu), but I don't want to add 'Admin Person' to that mapping, as if there are multiple curators using Canto, then 'Admin Person' could be more than one person.

I thought that the problem might be in Canto, as I thought that normally when  a curator 'takes on' a paper then the curator value gets assigned to them, overwriting what is already there ? (I don't know what buttons they have to press to make that happen). 

This is the first time we've seen 'Admin Person' in the output - we thought it might be due to the recent update of data.

@arzuozturk said that "Since the update, there are now papers with Admin Person as both
Corresponding author and Current curator ( I believe these are the
newly loaded ones) and papers with Vitor as Corresponding author and
Admin Person as Current Curator (and these might be the old ones)."

She thinks the problem ones might be cases where she had started (but not exported) the curation before the update, and so it might not be a problem moving forward for new papers (as a new paper she started this week correctly changed Current Curator to herself when she took it on).

So perhaps we should see whether we get a similar problem next week to see whether this one needs investigating further

**Comment by kimrutherford** [comment] 2021-03-15 09:25
Hi Gillian and Arzu.

> I said I thought this was one for you ;)

I think you're right.

> I thought that the problem might be in Canto, as I thought that normally when a curator 'takes on' a paper then the curator value gets assigned to them, overwriting what is already there ? 

Yep, that's how it's supposed to work. When you start curating you should be able to change the curator on the first page:
![flycanto-curator-details-1](https://user-images.githubusercontent.com/90474/111123308-09dd6f80-85d4-11eb-9bfe-3637e89f58ed.png)

If there's a mistake the curator can be changed with the "Reassign" button at the top right while in the session.

Some of the older papers have Vitor as the corresponding author until he pointed out that he won't be doing all the curating.  :-)

So we now put "Admin Person" as the corresponding author and hence the default session curator.

Unfortunately the JSON loading code reset the curator to "Admin Person" for existing sessions where curation had started, approved or exported.  Sorry!

The good news is that the previous curator for each session is still in the database so I can easily undo that problem without changing any annotation.  I'll need to take FlyCanto offline for a couple of minutes to first make a full backup (I like backups) and then undo the "Admin Person" problem.

@arzuozturk please let me know when would be a good time to turn FlyCanto off for a couple of minutes.  I'll be working until 11am or so this morning.  If that's not good for you I'll do it overnight UK time.

I fixed the bug so it won't happen next time we load from JSON.

**Comment by arzuozturk** [comment] 2021-03-15 10:01
Hi Kim,

Thank you for looking into this.

You can turn off FlyCanto now. I am preparing a presentation and don't need Canto for now.

Best,
Arzu

-----
Arzu Ozturk Colak
FlyBase Curator
________________________________

**Comment by kimrutherford** [comment] 2021-03-15 10:10
Thanks Arzu.

I've fixed the database and restarted Canto.  It looks like it's all OK but I'll leave this issue open until the next time you generate phen records.

**Comment by arzuozturk** [comment] 2021-03-15 10:12
Great! Many thanks.

Arzu

-----
Arzu Ozturk Colak
FlyBase Curator
________________________________

**Comment by arzuozturk** [comment] 2021-04-21 13:07
Hi Kim,

This issue has repeated again. On this week's json file there are many records that have 'Current Curator: Admin Person'. Could you please take a look into this?

Thanks.

**Comment by kimrutherford** [comment] 2021-04-21 21:37
Hi Arzu.  Sorry about that!  I thought I had fixed the bug.  I'll put the session curators back to what they should be and have another look at the bug.

I'll need to take Canto offline while I fix things.  I'll do that at 2am or so UK time.

**Comment by kimrutherford** [comment] 2021-04-22 07:34
The curator problem should be fixed now.

And I've definitely fixed the bug this time.

**Comment by arzuozturk** [comment] 2021-04-22 09:22
Great! Many thanks.

**Closed** 2021-06-17 10:49 UTC
Labels: FlyBase, low priority
