### ISSUE TITLE
error message in existing session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1070] opened 2016-02-09 19:52 UTC
![worry](https://cloud.githubusercontent.com/assets/7359272/12928676/b2d54c4a-cf66-11e5-9e12-d03fa57ae01e.jpg)

**Comment by ValWood** [comment] 2016-02-09 19:53
couln't read genetics interactions from server error for this session. Not seen this before.
Val

**Comment by airvine** [comment] 2016-02-09 20:49
This sort of error usually occurs because of changes made to either the application or an ontology, such that the previously entered data is no longer compatible with the new version. For example, if an ontology term was used that no longer exists in the new version of the ontology file.

**Comment by kimrutherford** [comment] 2016-02-09 21:35
It looks like an interaction in the database is missing its interacting gene.  It's an easy fix, but the server is behaving oddly.  Canto is accessing its data fine but I can't query from the command line without getting an error.  I've copied the Canto data directory to me laptop and it's all OK here.  I'll need to do some Googling to solve it.

**Comment by kimrutherford** [comment] 2016-02-10 04:16
>  Canto is accessing its data fine but I can't query from the command line without getting an error

*red face*  - amateur mistake: the data files are owned by the canto user on the server so I couldn't access them logged in as me.  So that's a false alarm.

I've fixed the error from Canto you reported.  I've deleted a mangled annotation.  The annotation was for cut2 with evidence code Synthetic Lethality.

Val, could you check that no annotation is missing from the session?

I'm hoping this was caused by an old bug that has been fixed.  There are two other sessions that had this problem.  I've fixed them but they might need checking.  Both had a mangled annotation with a missing interacting gene.

http://curation.pombase.org/pombe/curs/a434def9c7a2a3d0 - Anne Paoletti, Dosage Growth Defect, SPCC4B3.15/mid1

This one we missing the evidence too so I think the bug comes from the pre-genotypes workflow:
http://curation.pombase.org/pombe/curs/a434def9c7a2a3d0 - Amanda Bird, SPAC25B8.19c/loz1

Val, could you close this when your happy with the sessions?

**Comment by ValWood** [comment] 2016-02-10 17:55
In this one
http://curation.pombase.org/pombe/curs/a434def9c7a2a3d0 - Anne Paoletti, Dosage Growth Defect, SPCC4B3.15/mid1
I don't see any annotation like this in the paper or in BioGRID? MAybe it was deleted?

and for this one
This one we missing the evidence too so I think the bug comes from the pre-genotypes workflow:
http://curation.pombase.org/pombe/curs/a434def9c7a2a3d0 - Amanda Bird, SPAC25B8.19c/loz1
it's the same session ID?

Something else is odd though:

the physical interaction in this session http://curation.pombase.org/pombe/curs/a434def9c7a2a3d0
Interactor A	Evidence code	Interactor B
mid1	Affinity Capture-Western (affinity captures)	mid1	
mid1	Affinity Capture-Luminescence (affinity captures)	plo1
mid1	PCA (interacts with)	plo1
mid1	PCA (interacts with)	rng2	

don't match the annotations we see for mid1 from this paper:
http://www.pombase.org/spombe/result/SPCC4B3.15#interactionPhysical
affinity captures	plo1	Polo kinase Plo1	Affinity Capture-Western	Almonacid M et al. (2011)
forms complex with	rng2	IQGAP	Reconstituted Complex	Almonacid M et al. (2011)
modified by	plo1	Polo kinase Plo1	Biochemical Activity	Almonacid M et al. (2011)


I am wondering if  these are papers that BIoGrid and we (or in this case Anne) curated at the same time, but we both did it differently, and the  confusion is to do with our biogrid synching not  being quite clever enough to cope with this. I don't know if we have even thought about this situation. I know we have dealt with corrections but I can't remember whose annotations 'trump' whose. I suggest this because of the difference and also because I have never seen the evidence code PCA before, has anyone else?

We might need to discuss this ticket on Friday?

**Comment by mah11** [comment] 2016-02-10 18:04
The Amanda Bird session is bf037075feb20f28, for PMID:24831008 (I know this because it also happens to have a term request, so I looked at it for curation ticket 799). BioRID has curated one interaction: bait adh1, prey loz1; evidence synthetic rescue. I can't tell from the session whether Amanda tried to add the same interaction or any others; it just shows the error message. I also haven't looked at the paper yet.

**Comment by kimrutherford** [comment] 2016-02-10 22:48
> I don't see any annotation like this in the paper or in BioGRID?

It could be that she started making an annotation as a test and didn't delete it.  I'm now sure it was a half finished annotation.

**Comment by mah11** [comment] 2016-02-11 11:22
I'm going to email Amanda soonish anyway, once I've added the FYPO term for that session, so I can ask about the interaction annotation too.

I won't mess with anything in the Anne Paoletti session ;)

**Comment by ValWood** [comment] 2016-02-11 13:40
I'll deal with Anne's session, will keep this ticket open....I'm still a little confused here.

**Comment by ValWood** [comment] 2016-02-12 15:51
PMID:2203537 (cut1 session) fixed

**Comment by ValWood** [comment] 2016-02-12 15:55
I think possibly the A Paoletti session has not yet been submitted to curators? I think that is why  it has the existing biogrid annotations and Anne's new ones are slightly different. If this can be confirmed, there is  need to check this as it will be checked when it  is completed and submitted.
val

**Comment by kimrutherford** [comment] 2016-06-09 04:29
> I'll deal with Anne's session, will keep this ticket open....I'm still a little confused here.

Hi Val.  Have you been able to sort this out.  Can I help?

**Comment by ValWood** [comment] 2016-06-09 09:31
Re Anne's session, I'm not sure where it is up to so I mailed her to see if she had submitted it. Once we get it through to approval we can check the details. I'm not sure if we need this ticket or not. I suspect it can be closed?

**Comment by kimrutherford** [comment] 2016-06-09 09:44
Yep, let's close this.  The original problem is fixed.

**Closed by kimrutherford** 2016-06-09 09:44 UTC
Labels: bug, low priority
