### ISSUE TITLE
Slow docker searching for email issue

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1650] opened 2018-10-28 15:25 UTC
I have searched for the issue that @jseager7 issued regarding the long wait between putting in curator details and going to the gene page, when using docker, but I am unable to find it so logging this ticket.

I have eliminated email as the issue as I have now successfully got email working on our docker instance of canto at hetzner and it sends email, however we still get the hang!

@kimrutherford you could try it here:

[http://demo-canto.phi-base.org/curs/d8d69bdf34b0bcaf](http://demo-canto.phi-base.org)

In the startup script I set:

```bash
--net=host
```

I used postfix on the server to do the sending.

I should note that in a local docker build on a vagrant machine with not email configured, it is also using v8 of the docker build but I am not seeing the same symptoms and wonder if it is more down to configuration of canto (considering that the demo-canto build is new and I believe the one @jseager7 built was also new)?

I will further investigate tomorrow.

**Comment by kimrutherford** [comment] 2018-10-28 18:52
> I have searched for the issue that @jseager7 issued regarding the long wait between putting in
> curator details and going to the gene page, when using docker, but I am unable to find it so logging
> this ticket.

It's probably: #1640

I'll try the Vagrant Canto to see if I can reproduce the slow down locally.

**Comment by kimrutherford** [comment] 2018-10-29 07:18
> I'll try the Vagrant Canto to see if I can reproduce the slow down locally.

It was slow for me unless I disabled sendmail in the container.

> I have eliminated email as the issue as I have now successfully got email working on our docker
> instance of canto at hetzner and it sends email, however we still get the hang!

I'm still suspicious that the email system is slowing things down.  I think it's worth trying once #1640 is done.

Could you send me your canto_deploy.yaml?

**Comment by barnabynorman** [comment] 2018-10-29 14:33
@kimrutherford sent canto_deploy.yaml as requested

**Comment by kimrutherford** [comment] 2018-10-29 20:06
> sent canto_deploy.yaml as requested

Thanks.  I couldn't see any problems.  In my setup I saw some slowness because the "implementation_classes" setting was wrong.

**Comment by barnabynorman** [comment] 2018-10-30 10:07
@kimrutherford I wonder if its the way canto (whatever its using to send), sends email?? I have (previously) tried sending email out of docker using php but even though docker is using the same network the message fails. I read that it was to do with adding the message to a queue that the mail system on the host knows nothing about. I wonder if the canto mail is more optimistic and waits for some discovery whereas the php mail just drops immediately.

If it is a mail config / incompatibility issue, would it be possible to configure canto to use an email account and send from an external service? Not sure where we would get that service, perhaps our host offers mail??

**Comment by jseager7** [comment] 2018-11-27 10:46
@kimrutherford Could we change the way the configuration is handled, so that if no email is configured, Canto just skips trying to send anything, rather than hanging? Alternatively, we could add one configuration setting that disables email globally, if that's easier.

**Comment by jseager7** [comment] 2018-11-27 10:48
I've just remembered about issue #1640, that already covers the configuration fix. Closing this now.

**Closed by jseager7** 2018-11-27 10:48 UTC
Labels: bug, low priority
