### ISSUE TITLE
duplicate alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1550] opened 2018-07-06 21:16 UTC
This seems familiar...

I created 2 alleles which happened to be the same.
I think I did this by renaming an  existing allele the same as another existing allele (I  changed one version
cdk9as(aaT120G) unknown

to existing
cdk9as(aaT120G)  WT

However the annotations we still spit between the 2 identical alleles.

I moved the annotations so all 7 annotations are now  on one copy, but I'm a bit worried to delete the empty copy in case it takes my annotations away.

![merge](https://user-images.githubusercontent.com/7359272/42400621-322cb62e-816a-11e8-9b95-b53d0a6d9067.jpg)

**Comment by ValWood** [comment] 2018-07-06 21:17
Its the first and last in this screenshot.

session is curs/8a66efe1aac64683

**Comment by kimrutherford** [comment] 2019-01-23 06:50
I had a look.  There are no duplicate alleles in the database.  The allele is in the database once but there are two genotype entries that contain that allele.  The genotype with no annotations can be safely deleted.

> I think I did this by renaming an existing allele the same as another existing allele

I didn't think that was possible?  I can't reproduce it.

**Comment by kimrutherford** [comment] 2019-01-23 06:54
> I didn't think that was possible? I can't reproduce it.

I was able to create two single allele genotypes, then edit one to have the same allele as the other.  Which I think is this issue: #1130

**Comment by ValWood** [comment] 2019-02-09 17:56
Is this a duplicate of #1130 then?

**Comment by kimrutherford** [comment] 2019-02-11 02:15
> Is this a duplicate of #1130 then?

I think so, so I'll close this.

**Closed by kimrutherford** 2019-02-11 02:15 UTC
Labels: bug, next
