### ISSUE TITLE
Can't delete "unknown" strain

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2391] opened 2021-01-25 16:22 UTC
In this session I wanted to delete "unknown" strain:

<img width="655" alt="Screenshot 2021-01-25 at 16 20 26" src="https://user-images.githubusercontent.com/7359272/105733261-42908f00-5f29-11eb-95cd-033fd82030cc.png">

But I get a message

Failed to remove strain
can't delete strain with name Unknown strain as there are genotypes in the session that reference that strain

However, there are no genotypes in the session?

curs/baeff7a059e5f6c4/edit_genes

**Comment by ValWood** [comment] 2021-01-25 16:23
Ignore. I need to select organism forst in genotype management...

**Comment by ValWood** [comment] 2021-01-25 16:24
I deleted the genotype, but I get the same message if I try to remove the "unknown" label

**Comment by ValWood** [comment] 2021-01-25 16:25
@jseager7  could you add the strain too.

**Comment by kimrutherford** [comment] 2021-01-26 00:00
@jseager7 if you can't get to the bottom of this could you send me the database for the session?  curs_baeff7a059e5f6c4.sqlite3

Thanks.

**Comment by jseager7** [comment] 2021-01-26 09:40
@ValWood Which 'Unknown strain' do you want deleted? They've been added for _Rhizoctonia solani_, _Beta vulgaris_, and _Nicotiana benthamiana_. Is it _Rhizoctonia solani_ that needs changing?

**Comment by ValWood** [comment] 2021-01-26 11:09
> Rhizoctonia solani that needs changing?
yes please.

**Comment by jseager7** [comment] 2021-01-27 12:18
I've just tested this myself on the main server and I think the problem is related to the database. Canto thinks there's still a genotype in the session with the Unknown strain assigned to it – even though there isn't – so it's probably still hanging around in the database because it didn't delete properly. I'll copy the session to my local version so I can inspect the database and see what's going on.

**Comment by jseager7** [comment] 2021-01-27 13:57
@kimrutherford Here's the contents of the `genotype` table for the session (only the relevant columns included).

It seems the offending genotype (4) has the old name for the unknown strain identifier, 'Unknown strain used'. The new system uses 'Unknown strain' instead. I suspect this happened because I changed the code without fixing existing values in the session databases; see https://github.com/pombase/canto/pull/2130.

genotype_id | identifier
-- | --
4 | Rhizoctonia-solani-wild-type-genotypeUnknown-strain-used
7 | baeff7a059e5f6c4-genotype-7
8 | Beta-vulgaris-wild-type-genotype-Unknown-strain
9 | Nicotiana-benthamiana-wild-type-genotype-Unknown-strain

I think to fix this everywhere I'll need a script that will amend the old genotype names in every session. Something like the following regular expression substitution should work (not sure if this is a valid Perl regular expression):

```perl
$identifier =~ s/Unknown-strain-used$/-Unknown-strain/;
```
That should amend the example above to the following:

> Rhizoctonia-solani-wild-type-genotype-Unknown-strain

**Comment by kimrutherford** [comment] 2021-01-28 02:07
I think the root cause of the problem is that the wild type genotypes are automatically created by the metagenotype code and are never deleted.  I think that's fixable.

> Does Canto update the strain names used in genotype identifiers when it reloads the strain list?

The names aren't updated but they are mostly there in the genotype identifiers to help with debugging.

**Comment by kimrutherford** [comment] 2021-01-28 05:45
> I think the root cause of the problem is that the wild type genotypes are automatically created by the metagenotype code and are never deleted.

Now I've thought about it that can't be reason because only host WT genotypes are created in this way but the problematic genotype is a pathogen WT genotype.  The host WT genotypes are automatically removed if there are no metagenotypes that need them.  There shouldn't be any WT pathogen genotypes in the database.  That's very strange.

But ...  Is this an old session?  I see from the Git log I see that Rhizoctonia solani was in the host organism list for a while.  If a metagenotype was added before that fix with a Rhizoctonia solani WT genotype then if the metagenotype was removed after the config change, Canto won't have known to automatically remove it.  It currently only checks for WT host genotypes to clean up / remove.

https://github.com/PHI-base/config/commit/ed34aa966f025f8861a4cc8b60cd4f444f72fa42  - Tue Oct 1 2019

That seems like an unfortunate sequence of events but it's all I can think of.

@jseager7  If that's the problem then the solution is to manually remove the genotype with:

```bash
>> sqlite3 curs_e3204c452a80b1b2.sqlite3
```
```sql
PRAGMA foreign_keys = ON;      -- Sqlite ignores foreign keys by default
delete from genotype where identifier = 'Rhizoctonia-solani-wild-type-genotypeUnknown-strain-used';
```
If the genotype is referenced you'll get an error and while need to dig deeper.

I'll fix the code so this doesn't happen again.

**Comment by kimrutherford** [comment] 2021-01-28 06:43
I just tried replicating this bug by making a metagenotype with a WT host, then changing the host to a pathogen in the config.  I couldn't reproduce this problem - the WT genotype was deleted no matter what I tried.  I'm stumped.  :-)

@jseager7: could you send me a copy of the database for that session?

**Comment by jseager7** [comment] 2021-01-28 10:38
@kimrutherford I've sent you the session database. I've had a look around myself and can't see anything that's obviously wrong. The only unusual thing seems to be the genotype identifier, but like you say, the code doesn't seem to pay attention to that.

**Comment by kimrutherford** [comment] 2021-01-28 11:01
Thanks James.  Yep, I can't see anything wrong either.  I think most likely this is an old session and the metagenotype that had a Rhizoctonia solani WT genotype was created and deleted before October 2019.  That was when I fixed the code to clean up the WT host genotypes when the metagenotype is deleted.

The genotype identifier still containing "Unknown-strain-used" is a big clue that it's an old session and old problem.

So I think I've convinced myself that this problem occurred long ago and the code has changed so that it won't happen again.  So I think the next step is to run the SQL is the comment above: https://github.com/pombase/canto/issues/2391#issuecomment-768815103

Thanks for your help with this.

**Comment by kimrutherford** [comment] 2021-01-28 11:05
I forgot to say that I've tweaked that code that cleans up after metagenotype deletion so that does an extra check and will also clean up any other weird pathogen WT genotypes if a metagenotype is deleted.

**Comment by jseager7** [comment] 2021-01-28 11:17
@kimrutherford I've applied the fix to the production server and it worked fine. I've deleted the strain and resubmitted the session. Thanks for all your help. I take it it's safe to assume that this problem won't have occurred anywhere else, as long as _Rhizoctonia solani_ is the only example of a host that became a pathogen? If so, feel free to close this issue.

**Comment by kimrutherford** [comment] 2021-01-28 12:01
Yep, I think it's safe to close this.  That was a bit of a mission.  :-)

**Closed by kimrutherford** 2021-01-28 12:01 UTC
Labels: PHI-Canto, bug
