### ISSUE TITLE
workflow causes duplicate base annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2558] opened 2022-04-11 09:36 UTC
We have a small issue with the current workflow.

if a user makes a new genetic interaction annotation using copy/edit, an additional "base phenotype annotation" is created:

<img width="823" alt="Screenshot 2022-04-11 at 10 31 36" src="https://user-images.githubusercontent.com/7359272/162710446-3beb70d5-0337-43ed-9a31-5b6ddcd6b203.png">

This is undesirable. However, it is expected behaviour for all other copy edits where the edits would alter the phenotype (i.e conditions, assayed using).

I wonder if the best solution would be to allow people to create additional interactions in this way, but to "collapse" the phenotype down into a single annotation with =1 gIs

**Comment by kimrutherford** [comment] 2022-04-25 03:57
> I wonder if the best solution would be to allow people to create additional interactions in this way, but to "collapse" the phenotype down into a single annotation

I can't think of a better plan at the moment but I hope we do find another way.  In all other cases "Copy and edit" makes a new row in the table so it's not going to be a great user interface if we implement this.

**Comment by ValWood** [comment] 2022-04-25 07:35
If the user duplicates and edits, but only edits/adds interactions, we could maybe 
add the interactiosn, but provide the user with a message:

"the original annotation was not duplicated, a new interaction has been added to the existing phenotype" with better wording?

**Comment by kimrutherford** [comment] 2022-05-24 06:14
> I wonder if the best solution would be to allow people to create additional interactions in this way, but to "collapse" the phenotype down into a single annotation 

Having thought it through, I can't come up with a better plan.  The code to detect duplicates won't be difficult, but I think my chances of getting it correct first time are low.  :-)

There are a few special cases to think about:
   - comments need to be merged
   - longer term, if the extension on the existing annotation is a same as the new one except for an extra relation should we:
      - ask the user what to do?
      - or just make the new, separate annotation?
      - merge the annotations without asking?
   - I wonder about the same thing for conditions and maybe term suggestions

This issue overlaps with: pombase/canto#1895
For both issues we need to detect duplicate annotations.

**Comment by kimrutherford** [comment] 2022-07-25 03:43
> There are a few special cases to think about:

(After reading pombase/canto#1205)

 - ignore the curator when checking for duplicate annotation - if a second annotation is made that is a duplicate of an existing, but with a different curator, we should keep the original

**Comment by kimrutherford** [comment] 2022-07-26 12:29
I've now completed pombase/canto#1895 (apart from bug fixing) so I'll work on this issue next.

**Comment by kimrutherford** [comment] 2022-08-08 09:22
After a some distractions and false starts I think this is done (apart from bugs).  Now if you "Copy and edit" but only change the interactions, it doesn't create a duplicate annotation.  Instead it merges the interactions with the annotation that you are copying.

There is one annoyance that I don't have an easy fix for yet: a message flashes up saying "Not storing: an identical annotation exists".  I'll try to change that to say something more helpful.

The changes are in the test Canto.

**Closed** 2022-09-14 05:13 UTC
Labels: high priority, interactions
