### ISSUE TITLE
avoid duplicated of 'phenotype annotations

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1934] opened 2019-06-11 11:27 UTC
Was trying to copy/edit phenotype annotations and ran into a couple of issues

1 - While Copy/edit one phenotype annotation from a genotype page and selecting a new genotype I managed to make the same annotation more than once

Using the denticle row 1 at the bottom
![Screenshot 2019-06-11 at 12 17 07](https://user-images.githubusercontent.com/33721108/59267867-3916be00-8c43-11e9-82bd-ab58730c5ad5.png)

Managed to make three equal annotations for the Alk[1]/wild-type genotype:
![Screenshot 2019-06-11 at 12 21 52](https://user-images.githubusercontent.com/33721108/59268000-9e6aaf00-8c43-11e9-93cf-9fb0d822dd09.png)

Duplicated annotations are not allowed when copy/edit and not changing any of th information, which is good. That is what I tried with the example below but note that the OK button is disabled:
![Screenshot 2019-06-11 at 12 25 15](https://user-images.githubusercontent.com/33721108/59268198-1638d980-8c44-11e9-86b4-2da6a53f8d0c.png)

Would it be possible to not allow these duplicated entries or collapse them into a single one?

**Comment by ValWood** [comment] 2019-06-11 12:13
I also noticed this recently
https://github.com/pombase/canto/issues/1895

I don't think we used to be able to create exact duplicate annotations?

**Comment by kimrutherford** [comment] 2019-06-11 22:25
> I don't think we used to be able to create exact duplicate annotations?

Are you thinking of creating exact duplicate genotypes?  There are no checks for duplicate annotation at the moment.

**Comment by ValWood** [comment] 2019-06-12 06:26
possibly!

**Comment by ValWood** [comment] 2019-09-18 10:27
Exact duplicate of  #1895

This should be disallowed. This will happen eventually (hopefully not too long)

**Closed by ValWood** 2019-09-18 10:27 UTC
Labels: FlyBase, discuss, low priority
