### ISSUE TITLE
Error when trying to add a new synonym 

### ISSUE THREAD

**Issue by PCarme** [pombase/canto#2851] opened 2024-07-29 10:03 UTC
I was reviewing a community curation in which the authors have used an existing shk1 allele called orb2-34 (orb2 is a synonym name for shk1). In the paper, they call this allele pak1-ts using another synonym name for shk1. When I tried to add pak1-ts as a synonym for orb2-34, I got this error :
<img width="624" alt="Screenshot 2024-07-29 at 10 57 37" src="https://github.com/user-attachments/assets/19c58bf7-afb2-443f-8358-2d5c494301f0">

**Comment by kimrutherford** [comment] 2024-07-30 03:53
Hi @PCarme 

I've been trying to reproduce this bug on my desktop.  But a different bug is preventing me.  :-)

If I try to edit the allele I can't because of "Fix the duplicate description to continue".  That's a bug because unknown alleles don't have descriptions.  I can't edit the allele so I'm wondering how you were able to add the synonym?  Perhaps you could demonstrate on the next call?

![image](https://github.com/user-attachments/assets/ae1ccbc1-c6fc-4839-968e-8dd19845b9e7)

**Comment by PCarme** [comment] 2024-07-30 08:14
OK, that's weird I didn't get this bug, but I can show the one I got during the group meeting.

**Comment by kimrutherford** [comment] 2024-07-31 05:40
After fixing the bug with unknown alleles (https://github.com/pombase/canto/issues/2851#issuecomment-2257405481  6922b50f4f328e7c33d65c75) we can't reproduce this bug.  So we'll close the issue for now.

**Closed by kimrutherford** 2024-07-31 05:40 UTC
Labels: bug, high priority
