### ISSUE TITLE
make genotype 'note/comment' visible

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2067] opened 2019-10-14 14:12 UTC
IIRC in FlyBase Canto allele notes appear as a "link" in the genotype description box. 
If this is the case can we do the same for PHI-Canto
?

**Comment by jseager7** [comment] 2019-10-15 09:24
It looks like this feature is only on the FlyBase branch (`flybase-canto`) at the moment; it could be merged early to the `master` branch to make it available in PHI-Canto (and all the other versions of Canto), but that will need input from @kimrutherford.

**Comment by kimrutherford** [comment] 2019-10-15 20:37
I have a little bit more to do on the notes interface, hopefully today.  Then I think we should aim to move PHI-Canto to the new code.

**Comment by kimrutherford** [comment] 2019-10-16 03:13
Hi @jseager7 

I think it's probably a good time to update your test Canto with the latest changes.  I've made a temporary branch for testing that contains all the changes: https://github.com/pombase/canto/tree/phi-canto-testing

You'll need to do the usual `upgrade_db.pl latest`.  After a backup.  :-)

To configure allele notes use the `allele_note_types` setting:
https://github.com/pombase/canto/blob/phi-canto-testing/root/docs/md/canto_admin/configuration_file.md#allele_note_types

If you just need one allele note you could do:

```
allele_note_types:
  note:
     display_name: Note
```

**Comment by kimrutherford** [comment] 2019-10-16 03:45
> If you just need one allele note you could do:

I've changed the configuration to be a list so that the order of the fields in the dialog can be specified.  So the example config is now:

```
allele_note_types:
   - name: note
     display_name: Note
```

**Comment by jseager7** [comment] 2019-10-16 09:54
I've done some testing, and there aren't any bugs with this as far as I can see. I can add and remove notes of multiple different types.

**Comment by kimrutherford** [comment] 2019-10-16 23:25
> I've done some testing, and there aren't any bugs with this as far as I can see.

Great.  Was that local testing or on the PHI-Canto test server?

**Comment by jseager7** [comment] 2019-10-17 09:31
> Was that local testing or on the PHI-Canto test server?

Local testing, but I could replicate it on the test and demo server too if necessary.

One thing I did notice during local testing was a possible regression in speed compared to the master branch, and I don't think it was just due to being in debug mode. The other curators have recently mentioned some slowdown in Canto &ndash; see https://github.com/pombase/canto/issues/2025#issuecomment-543079917 &ndash; but this could be unrelated. I'll try to confirm once I test it online.

**Comment by jseager7** [comment] 2019-10-17 10:48
@kimrutherford I must not have been paying attention when testing this the first time, because after testing this branch on the server I've noticed one severe bug and one potential bug that need addressing. I'll open new issues for these and link them here.

- - -

> One thing I did notice during local testing was a possible regression in speed compared to the master branch

Having tested, I think this is just due to the slowdown induced by local virtualisation, since there's no noticeable difference on the server.

- - -
Also, one oddity from testing is that the organism selector seems to have regressed to its default bootstrap appearance instead of the ordinary Canto style:

![image](https://user-images.githubusercontent.com/37659591/67002501-f2930d80-f0d3-11e9-85be-f6989ef831b5.png)

**Comment by jseager7** [comment] 2019-10-17 10:57
Also, there's a leftover `console.log` in `alleleNotesEditDialogCtrl`:

https://github.com/pombase/canto/blob/d4523ed0d2089dbac95b998d05cda9544ac6a606/root/static/js/canto-modules.js#L5066

**Comment by kimrutherford** [comment] 2019-10-18 04:10
> Also, there's a leftover console.log

Thanks.  I've removed that.

**Comment by kimrutherford** [comment] 2019-11-12 00:49
> Also, one oddity from testing is that the organism selector seems to have regressed to its
> default bootstrap appearance instead of the ordinary Canto style:

I think the Bootstrap style matches the rest of Canto better than the old style.

**Comment by jseager7** [comment] 2019-11-12 10:27
> I think the Bootstrap style matches the rest of Canto better than the old style.

That's fine then. I don't have any particular preference.

**Comment by kimrutherford** [comment] 2019-11-12 23:46
Hi James.  As we discussed, I've merged all the genotype-type and allele note changes into the master branch.  I've deleted the tickets/ticket-2015 and genotype-interactions branches.  The phi-canto-testing branch at GitHub is the same as master now.

**Closed by kimrutherford** 2019-11-12 23:46 UTC
Labels: PHI-Canto
