### ISSUE TITLE
Capturing "diseases" In PHI-Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2206] opened 2020-01-28 13:33 UTC
After discussion with @CuzickA  yesterday.

At present we have been adding a disease extension to PHIPO annotations. I'm really against this as it is repetitive and redundant and often it isn't clear which terms should have the disease association. It will be difficult for curators.

What we are trying to capture here is the association between a specific pathogen, and a disease, so we do not need to hook this onto multiple annotations.

Instead we would like a very simple interface where the user can select
1) pathogen ii) host and iii) disease.

This means that:

A. We  will only need to capture this information once per session

B.  Curators are more likely not to forget to add them (or get annoyed by adding them)

C. We can also make the correct  pathogen host association even if the experiment is performed using a pathogen and a normally non-infected host (i.e a rice blast experiment on Barley for example), because we can just add the correct host as a species for this purpose. This allows a researcher to query PHI-Base and locate all the experiments trying to model a specific disease  regardless of experimental host.

**Comment by jseager7** [comment] 2020-01-28 14:49
I've talked through this with @CuzickA, and I agree that this is a more efficient way to capture diseases.

I think we'd be able to create a new annotation type to capture diseases; it may be possible to adapt the existing ontology-based annotations to fit this.

However, there's a few issues that we'll need to think about:

### Relating diseases to phenotype annotations

In the pre-Canto version of PHI-base, every disease is a property of an interaction. While this doesn't always mean that the interaction causes the disease, it does mean there is an explicit relation (accurate or not) between an interaction and a disease.

By making diseases a separate annotation type, we only have an implicit link between diseases and interactions. If all we are capturing in PHI-Canto is a pathogen, host, and disease name, then we have to be much broader in the relation between interactions and diseases: I think the only logically sane relation is to match the pathogen and host of the disease to the pathogen and host of an interaction.

This could be a particular issue once PHI-base transitions to a gene-centric interface: there isn't really a clear link between a gene and a disease. The best we can do is to create a link from a gene, to the interactions involving that gene, to the diseases that match the pathogen and host of those interactions.

### Inclusion of strains

There may be cases where the disease is particular to a strain of a pathogen, especially in the case of [pathovars](https://en.wikipedia.org/wiki/Pathovar). Because we're not curating at taxonomic ranks lower than species, the pathovar is specified in the strain name, so the only way to be precise about which pathogen causes the disease is to include strains in the annotation type.

### Diseases particular to a tissue type

We may also find cases where the disease name changes depending on the tissue or substance that's being infected. One possible example is pneumonia changing to bacteremia as a bacterial infection spreads from the lungs to the blood. In both these cases the pathogen and host are the same, but the disease name is not.

I'm not sure how we would relate the pathogen-host interactions to the correct disease unless we also had a tissue type to relate them. We could choose to not make this relation, but this would mean that querying for pneumonia (for example) may return phenotypes that are not related to a lung infection. The user may be able to distinguish the relevant annotations by looking at the tissue type of the phenotype annotation, but that seems awkward.

### Diseases that relate to multiple pathogens

Some diseases are so generic (e.g. leaf spot, pneumonia, bacteremia) that they could implicate many different pathogens. Querying for these in PHI-base could return a lot of results that aren't of interest. Maybe we could work around this by allowing a pathogen to be specified as well (e.g. pneumonia + _Streptococcus pneumoniae_).

**Comment by kimrutherford** [comment] 2020-01-29 04:02
> Instead we would like a very simple interface where the user can select
>    pathogen ii) host and iii) disease.

Is this specific to the paper for the current session or should this be curated outside Canto as a more general thing?

**Comment by jseager7** [comment] 2020-01-29 10:12
> Is this specific to the paper for the current session or should this be curated outside Canto as a more general thing?

Not sure; back when I was reviewing records in PHI-base to clean up the disease list, it seemed like the disease was curated when it was mentioned in the paper, but this might not be true in all cases. 

Depending on how general the disease annotation ends up being, there could be a lot of redundancy across sessions where curators curate identical pathogen-host combinations. If we do choose to curate diseases within Canto, it would be nice to have a way to suggest existing diseases for the pathogens and hosts in your session.

The original plan was for the causes_disease extension values to be inferred based on the pathogen, host, and tissue type involved in the metagenotype. Maybe we could still do something like this with the disease as a separate annotation type. Is there any precedent in Canto for suggesting data that's already been entered in other sessions?

**Comment by ValWood** [comment] 2020-01-29 19:03
> Is this specific to the paper for the current session or should this be curated outside Canto as a more general thing?

It's kind of specific to the paper. At least the purpose is to enable PHI-base to identify papers which
 have studies related to specific diseases.

**Comment by kimrutherford** [comment] 2020-01-30 07:07
I think this needs some thought.  This sounds like a new sort of annotation because it's not attached to a gene or genotype.  It will need a new workflow / interface, additions to the database schema and changes to the JSON exporting.

**Comment by ValWood** [comment] 2020-01-30 09:20
OK, @CuzickA  I suggest that for now, we capture this in a Google spreadsheet including all of the info we want to capture associated with the PMID . That way, in a few weeks we will have a better idea of what is required and we can make up a Mock-up, and there is less chance we have over looked something.

Link to the spreadsheet from here.

This isn't so urgent as some tasks becasue it will be quick and easy to plug the annotations into the sessions afterwards.

**Comment by jseager7** [comment] 2020-01-30 10:33
> the purpose is to enable PHI-base to identify papers which have studies related to specific diseases.

I think we'll have to make it clear in the curator guidelines (and Canto itself) that curators should only be curating the disease name when it's under study by the paper – basically when the disease is _relevant_ – otherwise curators might start thinking they have to curate each disease implicated by each pathogen in the session (as if we were curating diseases as a separate objective).

**Comment by CuzickA** [comment] 2020-02-03 14:25
I have just started a spreadsheet as suggested above. It can be found here
https://docs.google.com/spreadsheets/d/1806Vhv58ngmql-Z5fIEl7k0BxGx4CQoqamlOYvNwYSk/edit?usp=sharing
I can add to it gradually as I re-check through the sessions

**Comment by ValWood** [comment] 2020-12-09 14:01
Discussion with @CuzickA and Kim H-K @ValWood 
Decided it would be useful to implement this pre-publication.
Will discuss at first meeting in New Year.

**Comment by jseager7** [comment] 2021-01-13 14:46
I've discussed this some more with @kimrutherford and @CuzickA and we were wondering whether we need to curate the disease name in the session, because I'd expect that the disease will often be linked to a pathogen-host interaction that is already known: for example _Fusarium graminearum_ + _Triticum aestivum_ = Fusarium ear blight. We already have over 15,000 records in PHI-base that have a pathogen, host, and disease related to each other, so we might be to relate diseases to publications outside of PHI-Canto (at some other point in the pipeline) with extra processing.

Specifically, if the main use of disease curation is to allow PHI-base users to look up papers that are related to a disease, then we can just use the list of diseases in PHI-base plus their pathogen–host combinations to inform a search system on the PHI-base website. In effect, the search would be a shorthand for all interactions that are annotated (via PHI-base legacy data) with the disease. For example, searching for 'Fusarium ear blight' would return all interactions involving _Fusarium graminearum_ and _Triticum aestivum_, plus any other pathogen and host combination that might have interactions related to the disease.

I think the only time we'd need to add diseases is when a novel pathogen–host combination is shown to cause an existing disease, or when an entirely new disease is described. If it's safe to assume that both of these cases will be infrequent, then it may be possible for admin curators to maintain a disease list outside of PHI-Canto. We could even explore adding this taxonomic information as relations within the PHI-base disease ontology (PHIDO).

**Comment by jseager7** [comment] 2021-01-13 15:03
Using the PHI-base list, here's an example of the pathogen–host combinations the user might get if they searched for 'Fusarium head blight' (a synonym of Fusarium ear blight):

Pathogen | Host
-- | --
Fusarium asiaticum | Triticum aestivum (bread wheat)
Fusarium graminearum | Arabidopsis thaliana (thale cress)
Fusarium graminearum | Brachypodium distachyon (stiff brome)
Fusarium graminearum | Glycine max (soybean)
Fusarium graminearum | Oryza sativa (rice)
Fusarium graminearum | Solanum lycopersicum (tomato)
Fusarium graminearum | Triticum aestivum (bread wheat)
Fusarium graminearum | Zea mays (maize)

To make things less overwhelming for users we could also allow the search to be constrained to one pathogen or one host, such as 'Fusarium ear blight _on_ bread wheat'.

**Comment by ValWood** [comment] 2021-01-13 17:34
I've always thought that the curation of diseases  fits better outside of the curation session itself. It is usually an orthogonal piece of information from another source, and applies to organism pairs rather than to specific annotations, so this suggestion makes me happy. It's also one less thing  required for the manuscript.

**Comment by jseager7** [comment] 2021-01-25 14:59
Closing this in favour of a new issue, in light of the (hopefully final) decision to curate diseases as an annotation type; see #2390.

**Closed by jseager7** 2021-01-25 14:59 UTC
Labels: PHI-Canto
