### ISSUE TITLE
No "finish" button on editing pop up, ontology term drill down

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1786] opened 2019-02-25 15:09 UTC
See
![no finish button](https://user-images.githubusercontent.com/7359272/53346642-597a7100-390f-11e9-81e2-a7e41721fc4f.jpg)

**Comment by jseager7** [comment] 2019-02-26 11:04
Hi @ValWood, I've tried to replicate this bug on my local Canto version, but I can't get this popup to display _without_ the Finish button &ndash; it's always there for me:

![confirm-term-finish](https://user-images.githubusercontent.com/37659591/53408386-38209000-39b6-11e9-9743-a22676cd26e5.PNG)

I've updated both Canto versions to the latest version of the code; could you check if this bug still happens, or could you provide more details about the exact annotation that you were editing? (e.g. 'GO molecular function' or an extension such as 'infects_tissue') Also, does this occur on 'Edit' or 'Copy and edit'?

**Comment by ValWood** [comment] 2019-02-26 11:12
I can't remember exactly @CuzickA ?

**Comment by CuzickA** [comment] 2019-02-26 11:31
This bug still happens for me.
We were in admin approval mode and trying to alter the phenotype. I will show @jseager7 on my machine.

**Comment by kimrutherford** [comment] 2019-02-27 03:41
That's a strange bug.  Do you remember which term you were looking at?

**Comment by jseager7** [comment] 2019-02-27 10:23
I think the term in question is 'Hypersensitive response absent'. The original bug appeared when in approval mode (with Alayne logged in as an admin), but it might appear in other modes. I meant to check this yesterday but didn't get the chance.

**Comment by CuzickA** [comment] 2019-03-01 12:25
Yes the bug appears with
'Hypersensitive response absent'
'Hypersensitive response present'
'Abolished Hypersensitive response'
'Delayed Hypersensitive response'

**Comment by kimrutherford** [comment] 2019-03-03 21:33
Hi.  Thanks for investigating this.

It took a bit of head scratching but I think I've worked out what's going on: there's a restriction (possibly bug?) in the Canto loading code and there's a problem with the PHIPO OBO file.

To keep things simple, Canto's ontology loading code ignores relations the go across namespaces.  All the terms and relations from a single namespace are processed and loaded, then it moves onto the next namespace.

When deciding which terms are root terms it just looks to see if there are any parents terms.  But it only looks for those parents in the same namespace as the child.

Unfortunately some of the terms on the PHIPO.obo file don't have an explicit namespace.  Here's an example:

```
 [Term]
 id: PHIPO:0000217
 name: pathogen host interaction primary metabolic process phenotype
 def: "A pathogen host interaction phenotype that affects the chemical reactions ..." []
 comment: Definition adapted from GO:0044238 primary metabolic process
 xref: GO:0044238
 is_a: PHIPO:0000220 ! pathogen host interaction metabolic process phenotype
 created_by: alaynecuzick
 creation_date: 2018-10-01T13:43:20Z
```

If a term doesn't have an explicit namespace it gets given the default-namespace from the header of the OBO file.   If there is no "default-namespace" it uses the "ontology" header.  For PHIPO that's "ontology: phipo".  So for PHIPO:0000217 above, the loading code assumes that the namespace is "phipo".

The parent term does have a namespace:
```
[Term]
id: PHIPO:0000220
name: pathogen host interaction metabolic process phenotype
namespace: pathogen_host_interaction_phenotype
...
```

So PHIPO:0000217 has the namespace "phipo" and it's "is_a" parent has the namespace "pathogen_host_interaction_phenotype".  Because the parent is in a different namespace, it's ignored so Canto thinks PHIPO:0000217 is a root term.

Here is a list of all the terms with no explicit namespace, queried from my Canto database:

| ID | name |
| --- | --- |
|PHIPO:0000162|organism growth phenotype|
|PHIPO:0000177|yeast like growth form phenotype|
|PHIPO:0000184|pathogen adhesion to host phenotype|
|PHIPO:0000217|pathogen host interaction primary metabolic process phenotype|
|PHIPO:0000445|pathogen host interaction with host cell death phenotype|
|PHIPO:0000450|normal pathogen peptidase activity|
|PHIPO:0000461|host programmed cell death response to pathogen|
|PHIPO:0000462|host cell apoptosis in response to pathogen phenotype|
|PHIPO:0000463|host autophagy response to pathogen phenotype|
|PHIPO:0000464|host necrosis in response to pathogen|
|PHIPO:0000465|host cell injury from pathogen phenotype|
|PHIPO:0000466|host hypersensitive response to pathogen phenotype|
|PHIPO:0000474|normal host hypersensitive response to pathogen|
|PHIPO:0000475|abnormal host hypersensitive response to pathogen|
|PHIPO:0000476|normal host cell apoptosis in response to pathogen|
|PHIPO:0000477|abnormal host cell apoptosis in response to pathogen|
|PHIPO:0000478|normal host autophagy response to pathogen|
|PHIPO:0000479|abnormal host autophagy response to pathogen|
|PHIPO:0000480|normal host necrosis in response to pathogen|
|PHIPO:0000481|abnormal host necrosis in response to pathogen|
|PHIPO:0000505|phenotype|
|PHIPO:0000506|single organism|
|PHIPO:0000507|pathogen host interaction|

**Comment by CuzickA** [comment] 2019-03-04 12:30
Thanks for the above list @kimrutherford it is really helpful as its to easy to miss adding all the information in Protege. As discussed perhaps we could add some data checks for the future.

I have now added namespaces to above. I have added 'phipo' to phenotype and 'single organism phenotype' to single organism and 'pathogen host interaction phenotype' to pathogen host interaction as discussed.

Before testing if this has fixed the problem, I will need to make a release and await PHI-Canto ontology loading.

**Comment by kimrutherford** [comment] 2019-03-26 03:49
Hi @CuzickA 

I've loaded the latest phipo.obo file in my local Canto and it's much better now.  I noticed that there is still one term without a namespace in the OBO file:

```
[Term]
id: PHIPO:0000474
name: normal host hypersensitive response to pathogen
def: "pathogen_host_interaction_phenotype" []
is_a: PHIPO:0000466 ! host hypersensitive response to pathogen phenotype
created_by: alaynecuzick
creation_date: 2019-01-14T12:21:01Z
```

**Comment by jseager7** [comment] 2019-03-26 10:33
The fact that PHIPO:0000474 'normal host hypersensitive response to pathogen' doesn't have a namespace also leads to buggy behaviour with its child terms: specifically, PHIPO:0000192 'hypersensitive response present' and PHIPO:0000182 'hypersensitive response absent'. These terms still show the same bug where the Finish button doesn't appear. I've also noticed that when you try to create an annotation using these child terms (rather than editing an existing annotation), Canto shows the following message:

> This term should not be used for direct annotations. Please select a more specific term, or suggest a new descendant term.

I'm not quite sure why that happens; perhaps the namespace that the term is automatically assigned is marked as _do not annotate_. Regardless, it should be easily fixed by adding the missing namespaces. I can do that myself.

**Comment by jseager7** [comment] 2019-03-26 10:41
While testing, I've also noticed that PHIPO:0000507 'pathogen host interaction' isn't marked as _do not annotate_, when it probably should be.

**Comment by jseager7** [comment] 2019-03-26 12:31
I've now fixed the previously mentioned problems in the `phipo.obo` file (see https://github.com/PHI-base/phipo/commit/213db142403b191ed217130d193559c40b6de626), and reloaded the ontology on PHI-Canto's servers. It seems like the problem is fixed now, since the Finish button appears for all of the terms in the list above.

I've also checked for any remaining PHIPO terms that are lacking a namespace, and there don't seem to be any. Closing this issue now.

**Closed by jseager7** 2019-03-26 12:31 UTC
Labels: PHI-Canto, bug, high priority

**Comment by kimrutherford** [comment] 2019-04-04 05:37
> I'm not quite sure why that happens; perhaps the namespace that the term is automatically assigned
> is marked as do not annotate.

Because the term doesn't have a "namespace:" field, it gets the default namespace.  So the term has a different namespace to its parent which causes the Canto loader to decide that it must be a top-level term.  This logic works for the most ontologies but is obviously a bit dodgy.

Because the term gets marked as a top-level/root term it ends up in the do-not-annotation subset.
