### ISSUE TITLE
geneotypes are incorrect for the direction of the prompt

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2640] opened 2022-09-20 11:19 UTC
When. I try to add a "dosage growth defect annotation"
to
skb1+[Overexpression]
wee1Δ

the prompt is the wrong way around:

<img width="1057" alt="Screenshot 2022-09-20 at 12 10 49" src="https://user-images.githubusercontent.com/7359272/191244236-081f92e4-6242-4323-9efa-c957d6990b20.png">

I think this might be because the prompts changed recently, but the prompts don't always work in the same direction

**Comment by manulera** [comment] 2022-09-20 12:43
Duplicate of #2610

**Closed** 2022-09-21 05:24 UTC
Labels: bug, interactions
